const hsk1 = [
    { chinese: "这个", pinyin: "zhè ge", english: "this", sampleChinese: "这个东西很好，你喜欢吗？", sampleEnglish: "This thing is good, do you like it?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "爱", pinyin: "ài", english: "love", sampleChinese: "他们之间有深厚的爱。", sampleEnglish: "There is deep love between them.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "爱好", pinyin: "ài hào", english: "hobby", sampleChinese: "我的爱好是弹吉他。", sampleEnglish: "My hobby is playing the guitar.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "八", pinyin: "bā", english: "eight", sampleChinese: "八点钟见！", sampleEnglish: "See you at eight o'clock!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "爸爸", pinyin: "bà ba", english: "dad, father", sampleChinese: "我的爸爸每天早上都做早饭。", sampleEnglish: "My dad makes breakfast every morning.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "吧", pinyin: "ba", english: "particle for suggestion", sampleChinese: "我们去吃饭吧，然后看电影。", sampleEnglish: "Let's go eat and then watch a movie.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "白", pinyin: "bái", english: "white", sampleChinese: "她穿了一件白色的裙子。", sampleEnglish: "She is wearing a white dress.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "白天", pinyin: "bái tiān", english: "daytime", sampleChinese: "白天是学习的好时机。", sampleEnglish: "Daytime is a good time for studying.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "百", pinyin: "bǎi", english: "hundred", sampleChinese: "这本书有一百页。", sampleEnglish: "This book has one hundred pages.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "班", pinyin: "bān", english: "class", sampleChinese: "我在二班上课。", sampleEnglish: "I have classes in Class 2.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "半", pinyin: "bàn", english: "half", sampleChinese: "等我半小时，我就到了。", sampleEnglish: "Wait for me half an hour, and I'll be there.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "半年", pinyin: "bàn nián", english: "half a year", sampleChinese: "我去年度过了半年在国外。", sampleEnglish: "I spent half a year abroad last year.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "半天", pinyin: "bàn tiān", english: "half a day", sampleChinese: "上午半天工作，下午休息。", sampleEnglish: "Work half a day in the morning, rest in the afternoon.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "帮", pinyin: "bāng", english: "to help", sampleChinese: "我可以帮你做作业。", sampleEnglish: "I can help you with your homework.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "帮忙", pinyin: "bāng máng", english: "to help", sampleChinese: "他经常帮忙照顾老人。", sampleEnglish: "He often helps take care of the elderly.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "包", pinyin: "bāo", english: "bag", sampleChinese: "我的包丢了，里面有我的钱包。", sampleEnglish: "I lost my bag, and my wallet was inside.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "包子", pinyin: "bāo zi", english: "steamed bun", sampleChinese: "我喜欢吃肉包子。", sampleEnglish: "I like eating meat buns.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "杯", pinyin: "bēi", english: "cup", sampleChinese: "请给我一杯咖啡。", sampleEnglish: "Please give me a cup of coffee.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "杯子", pinyin: "bēi zi", english: "cup, glass", sampleChinese: "这个玻璃杯子很漂亮。", sampleEnglish: "This glass is very beautiful.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "北", pinyin: "běi", english: "north", sampleChinese: "北风吹得很凉爽。", sampleEnglish: "The north wind blows cool.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "北边", pinyin: "běi biān", english: "north", sampleChinese: "北京在中国的北边。", sampleEnglish: "Beijing is in the north of China.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "北京", pinyin: "běi jīng", english: "Beijing", sampleChinese: "北京是中国的首都。", sampleEnglish: "Beijing is the capital of China.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "本", pinyin: "běn", english: "this, root", sampleChinese: "这本书很有趣。", sampleEnglish: "This book is very interesting.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "本子", pinyin: "běn zi", english: "notebook", sampleChinese: "我的笔记本子用完了。", sampleEnglish: "I've finished using my notebook.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "比", pinyin: "bǐ", english: "compare", sampleChinese: "他比我更高。", sampleEnglish: "He is taller than me.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "别", pinyin: "bié", english: "don't, other", sampleChinese: "别走，等等我！", sampleEnglish: "Don't go, wait for me!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "别的", pinyin: "bié de", english: "other", sampleChinese: "我还有别的事情要做。", sampleEnglish: "I have other things to do.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "别人", pinyin: "bié rén", english: "other people", sampleChinese: "别人的问题不是你的责任。", sampleEnglish: "Other people's problems are not your responsibility.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "病", pinyin: "bìng", english: "illness", sampleChinese: "感冒是一种常见的疾病。", sampleEnglish: "The common cold is a common illness.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "病人", pinyin: "bìng rén", english: "patient", sampleChinese: "医院里有很多病人。", sampleEnglish: "There are many patients in the hospital.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "不大", pinyin: "bù dà", english: "not big", sampleChinese: "这个房间不大，但很舒适。", sampleEnglish: "This room is not big, but it's very comfortable.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "不对", pinyin: "bù duì", english: "not correct", sampleChinese: "你的答案不对。", sampleEnglish: "Your answer is not correct.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "不客气", pinyin: "bù kè qi", english: "you're welcome", sampleChinese: "谢谢你的帮忙。不客气。", sampleEnglish: "Thank you for your help. You're welcome.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "不用", pinyin: "bù yòng", english: "not necessary", sampleChinese: "不用担心，一切都会好的。", sampleEnglish: "Don't worry, everything will be fine.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "不", pinyin: "bù", english: "not", sampleChinese: "他不喜欢吃辣的食物。", sampleEnglish: "He doesn't like spicy food.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "菜", pinyin: "cài", english: "vegetable, dish", sampleChinese: "我喜欢吃炒菜。", sampleEnglish: "I like to eat stir-fried vegetables.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "茶", pinyin: "chá", english: "tea", sampleChinese: "你想要喝茶吗？", sampleEnglish: "Would you like to have some tea?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "差", pinyin: "chà", english: "difference, to lack", sampleChinese: "这两个地方差不多。", sampleEnglish: "These two places are almost the same.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "常", pinyin: "cháng", english: "often", sampleChinese: "我常常去图书馆学习。", sampleEnglish: "I often go to the library to study.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "常常", pinyin: "cháng cháng", english: "often", sampleChinese: "她常常在晚饭后锻炼。", sampleEnglish: "She often exercises after dinner.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "唱", pinyin: "chàng", english: "to sing", sampleChinese: "他喜欢唱流行歌曲。", sampleEnglish: "He likes to sing pop songs.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "唱歌", pinyin: "chàng gē", english: "to sing a song", sampleChinese: "我们一起唱歌吧！", sampleEnglish: "Let's sing a song together!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "车", pinyin: "chē", english: "car", sampleChinese: "我没有自己的车。", sampleEnglish: "I don't have my own car.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "车票", pinyin: "chē piào", english: "ticket", sampleChinese: "你买了火车票吗？", sampleEnglish: "Did you buy a train ticket?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "车上", pinyin: "chē shàng", english: "on the vehicle", sampleChinese: "在车上，请系好安全带。", sampleEnglish: "On the vehicle, please fasten your seatbelt.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "车站", pinyin: "chē zhàn", english: "train station", sampleChinese: "我要去火车站接我的朋友。", sampleEnglish: "I'm going to the train station to pick up my friend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "吃", pinyin: "chī", english: "to eat", sampleChinese: "我们一起去吃晚饭吧。", sampleEnglish: "Let's go eat dinner together.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "吃饭", pinyin: "chī fàn", english: "to have a meal", sampleChinese: "现在是吃饭的时间。", sampleEnglish: "Now is the time to have a meal.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "出", pinyin: "chū", english: "to go out", sampleChinese: "我今天不想出门。", sampleEnglish: "I don't want to go out today.", rightInARow: 0, nextReviewDate: Date.now() },    
    { chinese: "出来", english: "to come out", sampleChinese: "请出来，我们需要谈一谈。", sampleEnglish: "Please come out; we need to talk.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "出去", pinyin: "chūqù", english: "to go out", sampleChinese: "我们出去散步吧。", sampleEnglish: "Let's go out for a walk.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "穿", pinyin: "chuān", english: "to wear", sampleChinese: "今天天气冷，记得穿暖和一点。", sampleEnglish: "It's cold today, remember to wear something warm.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "床", pinyin: "chuáng", english: "bed", sampleChinese: "我想躺在床上休息一下。", sampleEnglish: "I want to lie on the bed and rest for a while.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "次", pinyin: "cì", english: "time, number of times", sampleChinese: "这是我第二次来中国。", sampleEnglish: "This is my second time in China.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "从", pinyin: "cóng", english: "from", sampleChinese: "我从学校回家。", sampleEnglish: "I'm going home from school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "错", pinyin: "cuò", english: "wrong", sampleChinese: "这个答案是错的。", sampleEnglish: "This answer is wrong.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "打", pinyin: "dǎ", english: "to hit", sampleChinese: "他不应该打其他小孩。", sampleEnglish: "He shouldn't hit other kids.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "打车", pinyin: "dǎchē", english: "to take a taxi", sampleChinese: "我们需要打车去机场。", sampleEnglish: "We need to take a taxi to the airport.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "打电话", pinyin: "dǎ diànhuà", english: "to make a phone call", sampleChinese: "我给你打电话。", sampleEnglish: "I'll call you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "打开", pinyin: "dǎkāi", english: "to open", sampleChinese: "请帮我打开窗户。", sampleEnglish: "Please help me open the window.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "打球", pinyin: "dǎqiú", english: "to play ball", sampleChinese: "他们每周末打篮球。", sampleEnglish: "They play basketball every weekend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "大", pinyin: "dà", english: "big", sampleChinese: "这个城市非常大。", sampleEnglish: "This city is very big.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "大学", pinyin: "dàxué", english: "university", sampleChinese: "我在大学学习计算机科学。", sampleEnglish: "I study computer science at the university.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "大学生", pinyin: "dàxuéshēng", english: "university student", sampleChinese: "他是一名大学生。", sampleEnglish: "He is a university student.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "到", pinyin: "dào", english: "to arrive, to reach", sampleChinese: "我们准时到达了目的地。", sampleEnglish: "We arrived at our destination on time.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "得到", pinyin: "dédào", english: "to obtain", sampleChinese: "他终于得到了他梦寐以求的工作。", sampleEnglish: "He finally obtained the job he had been dreaming of.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地", pinyin: "dì", english: "ground", sampleChinese: "这片地适合建房子吗？", sampleEnglish: "Is this ground suitable for building a house?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "的", pinyin: "de", english: "of", sampleChinese: "这是我的书的封面。", sampleEnglish: "This is the cover of my book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "等", pinyin: "děng", english: "to wait", sampleChinese: "请等一下，我很快就回来。", sampleEnglish: "Please wait for a moment; I'll be back soon.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地", pinyin: "dì", english: "ground", sampleChinese: "他摔倒在地上。", sampleEnglish: "He fell to the ground.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地点", pinyin: "dìdiǎn", english: "location", sampleChinese: "我们明天在同一个地点见面。", sampleEnglish: "Let's meet at the same location tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地方", pinyin: "dìfāng", english: "place", sampleChinese: "这是一个美丽的地方。", sampleEnglish: "This is a beautiful place.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地上", pinyin: "dìshàng", english: "on the ground", sampleChinese: "有一只猫躺在地上晒太阳。", sampleEnglish: "A cat is lying on the ground, basking in the sun.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地图", pinyin: "dìtú", english: "map", sampleChinese: "我迷路了，你能给我看看地图吗？", sampleEnglish: "I'm lost, can you show me the map?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "弟弟", pinyin: "dìdì", english: "younger brother", sampleChinese: "我的弟弟很聪明。", sampleEnglish: "My younger brother is very smart.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "第", pinyin: "dì", english: "number, order", sampleChinese: "这是第一次我来中国。", sampleEnglish: "This is the first time I've come to China.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "点", pinyin: "diǎn", english: "point, o'clock", sampleChinese: "现在是八点。", sampleEnglish: "It's eight o'clock now.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电", pinyin: "diàn", english: "electricity", sampleChinese: "这个设备需要电吗？", sampleEnglish: "Does this device need electricity?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电话", pinyin: "diànhuà", english: "phone, telephone", sampleChinese: "我会给你打电话。", sampleEnglish: "I'll call you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电脑", pinyin: "diànnǎo", english: "computer", sampleChinese: "我每天都使用电脑工作。", sampleEnglish: "I use a computer for work every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电视", pinyin: "diànshì", english: "television", sampleChinese: "我喜欢看电视。", sampleEnglish: "I like watching TV.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电视机", pinyin: "diànshìjī", english: "TV set", sampleChinese: "电视机放在客厅里。", sampleEnglish: "The TV set is in the living room.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电影", pinyin: "diànyǐng", english: "movie", sampleChinese: "我们周末去看电影吧。", sampleEnglish: "Let's go watch a movie this weekend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电影院", pinyin: "diànyǐngyuàn", english: "cinema", sampleChinese: "这家电影院有最新的电影。", sampleEnglish: "This cinema has the latest movies.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "东", pinyin: "dōng", english: "east", sampleChinese: "太阳从东方升起。", sampleEnglish: "The sun rises in the east.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "东边", pinyin: "dōngbiān", english: "east", sampleChinese: "图书馆在学校的东边。", sampleEnglish: "The library is on the east side of the school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "东西", pinyin: "dōngxi", english: "thing, stuff", sampleChinese: "我忘记了带东西。", sampleEnglish: "I forgot to bring my stuff.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "动", pinyin: "dòng", english: "to move", sampleChinese: "小狗在草地上动。", sampleEnglish: "The puppy is moving on the grass.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "动作", pinyin: "dòngzuò", english: "action", sampleChinese: "他的动作很迅速。", sampleEnglish: "His actions are very fast.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "都", pinyin: "dōu", english: "all, both", sampleChinese: "他们都喜欢吃披萨。", sampleEnglish: "They both like pizza.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "读", pinyin: "dú", english: "to read", sampleChinese: "我喜欢读小说。", sampleEnglish: "I like to read novels.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "读书", pinyin: "dúshū", english: "to study, to read a book", sampleChinese: "晚上我常常在图书馆读书。", sampleEnglish: "I often study at the library in the evening.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "对", pinyin: "duì", english: "correct, to face", sampleChinese: "这是正确的答案。", sampleEnglish: "This is the correct answer.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "对不起", pinyin: "duìbuqǐ", english: "sorry", sampleChinese: "对不起，我迟到了。", sampleEnglish: "Sorry, I'm late.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "多", pinyin: "duō", english: "many, much", sampleChinese: "这个城市有很多高楼。", sampleEnglish: "This city has many tall buildings.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "多少", pinyin: "duōshǎo", english: "how much, how many", sampleChinese: "你们有多少钱？", sampleEnglish: "How much money do you have?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "饿", pinyin: "è", english: "hungry", sampleChinese: "我饿了，我要吃午饭。", sampleEnglish: "I'm hungry; I want to have lunch.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "儿子", pinyin: "érzi", english: "son", sampleChinese: "我儿子在学校学习。", sampleEnglish: "My son is studying at school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "二", pinyin: "èr", english: "two", sampleChinese: "二加二等于四。", sampleEnglish: "Two plus two equals four.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "饭", pinyin: "fàn", english: "meal, cooked rice", sampleChinese: "晚饭的时候我喜欢吃米饭。", sampleEnglish: "I like to eat rice for dinner.", rightInARow: 0, nextReviewDate: Date.now() },    
    { chinese: "饭店", english: "restaurant", sampleChinese: "我们去附近的饭店吃晚饭。", sampleEnglish: "Let's go to a nearby restaurant for dinner.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "房间", pinyin: "fángjiān", english: "room", sampleChinese: "这个酒店的房间很宽敞。", sampleEnglish: "The rooms in this hotel are spacious.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "房子", pinyin: "fángzi", english: "house", sampleChinese: "我梦想有一所漂亮的房子。", sampleEnglish: "I dream of having a beautiful house.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "放", pinyin: "fàng", english: "to put, to place", sampleChinese: "把书放在桌子上。", sampleEnglish: "Put the book on the table.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "放假", pinyin: "fàngjià", english: "to have a holiday", sampleChinese: "每年夏天，我都会放假去旅行。", sampleEnglish: "Every summer, I take a holiday to travel.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "放学", pinyin: "fàngxué", english: "school's out", sampleChinese: "孩子们放学后通常会去公园玩。", sampleEnglish: "Children usually go to the park to play after school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "飞", pinyin: "fēi", english: "to fly", sampleChinese: "飞机从机场起飞。", sampleEnglish: "The plane takes off from the airport.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "飞机", pinyin: "fēijī", english: "airplane", sampleChinese: "我坐飞机去了上海。", sampleEnglish: "I took a plane to Shanghai.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "非常", pinyin: "fēicháng", english: "very", sampleChinese: "今天天气非常热。", sampleEnglish: "The weather is very hot today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "分", pinyin: "fēn", english: "minute, to divide", sampleChinese: "这个任务需要十分钟。", sampleEnglish: "This task will take ten minutes.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "风", pinyin: "fēng", english: "wind", sampleChinese: "海边的风非常凉爽。", sampleEnglish: "The wind by the sea is very refreshing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "干", pinyin: "gàn", english: "to do", sampleChinese: "他每天都干很多工作。", sampleEnglish: "He does a lot of work every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "干净", pinyin: "gānjìng", english: "clean", sampleChinese: "这个房间很干净。", sampleEnglish: "This room is very clean.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "干", pinyin: "gān", english: "dry", sampleChinese: "请把湿衣服晾干。", sampleEnglish: "Please hang wet clothes to dry.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "干什么", pinyin: "gàn shénme", english: "to do what", sampleChinese: "你今天晚上要干什么？", sampleEnglish: "What are you going to do tonight?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "高", pinyin: "gāo", english: "tall, high", sampleChinese: "这座山非常高。", sampleEnglish: "This mountain is very high.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "高兴", pinyin: "gāoxìng", english: "happy", sampleChinese: "他听到这个好消息后非常高兴。", sampleEnglish: "He was very happy when he heard the good news.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "告诉", pinyin: "gàosu", english: "to tell", sampleChinese: "请告诉我你的名字。", sampleEnglish: "Please tell me your name.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "哥哥", pinyin: "gēge", english: "older brother", sampleChinese: "我哥哥比我大两岁。", sampleEnglish: "My older brother is two years older than me.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "歌", pinyin: "gē", english: "song", sampleChinese: "这是一首美丽的歌曲。", sampleEnglish: "This is a beautiful song.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "个", pinyin: "gè", english: "measure word for individuals", sampleChinese: "我有一个好朋友。", sampleEnglish: "I have a good friend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "给", pinyin: "gěi", english: "to give", sampleChinese: "我给你一本书。", sampleEnglish: "I'll give you a book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "跟", pinyin: "gēn", english: "with", sampleChinese: "我今天跟朋友一起去购物。", sampleEnglish: "I'm going shopping with friends today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "工人", pinyin: "gōngrén", english: "worker", sampleChinese: "这个工人每天都在建造房子。", sampleEnglish: "The worker is building houses every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "工作", pinyin: "gōngzuò", english: "work, to work", sampleChinese: "我明天要早点去工作。", sampleEnglish: "I need to go to work early tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "关", pinyin: "guān", english: "to close", sampleChinese: "请把门关上。", sampleEnglish: "Please close the door.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "关上", pinyin: "guānshàng", english: "to close (something)", sampleChinese: "关上窗户，不然会下雨进来。", sampleEnglish: "Close the window, or rain will come in.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "贵", pinyin: "guì", english: "expensive", sampleChinese: "这个手表很贵。", sampleEnglish: "This watch is very expensive.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "国", pinyin: "guó", english: "country", sampleChinese: "中国是一个大国。", sampleEnglish: "China is a big country.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "国家", pinyin: "guójiā", english: "country", sampleChinese: "每个国家都有自己的文化。", sampleEnglish: "Every country has its own culture.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "国外", pinyin: "guówài", english: "overseas", sampleChinese: "我梦想去国外旅行。", sampleEnglish: "I dream of traveling overseas.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "过", pinyin: "guò", english: "to pass, to spend", sampleChinese: "时间过得真快。", sampleEnglish: "Time passes quickly.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "还", pinyin: "hái", english: "still, yet", sampleChinese: "我还没吃早饭。", sampleEnglish: "I haven't eaten breakfast yet.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "还是", pinyin: "háishì", english: "or", sampleChinese: "你喜欢咖啡还是茶？", sampleEnglish: "Do you like coffee or tea?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "还有", pinyin: "háiyǒu", english: "also, furthermore", sampleChinese: "我要买苹果还有橙子。", sampleEnglish: "I want to buy apples and oranges.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "孩子", pinyin: "háizi", english: "child", sampleChinese: "这是我的孩子，她很聪明。", sampleEnglish: "This is my child; she is very smart.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "汉语", pinyin: "hànyǔ", english: "Chinese language", sampleChinese: "学习汉语需要耐心。", sampleEnglish: "Learning Chinese language requires patience.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "汉字", pinyin: "hànzì", english: "Chinese characters", sampleChinese: "汉字是中国文字的一部分。", sampleEnglish: "Chinese characters are part of Chinese writing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "好", pinyin: "hǎo", english: "good", sampleChinese: "这是一个好消息。", sampleEnglish: "This is good news.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "好吃", pinyin: "hǎochī", english: "delicious", sampleChinese: "这个菜真好吃。", sampleEnglish: "This dish is really delicious.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "好看", pinyin: "hǎokàn", english: "good-looking", sampleChinese: "她穿这件衣服很好看。", sampleEnglish: "She looks good in this outfit.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "好听", pinyin: "hǎotīng", english: "pleasant to hear", sampleChinese: "这首歌非常好听。", sampleEnglish: "This song is very pleasant to hear.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "好玩儿", pinyin: "hǎowánr", english: "fun", sampleChinese: "这个游乐园很好玩儿。", sampleEnglish: "This amusement park is a lot of fun.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "号", pinyin: "hào", english: "number", sampleChinese: "今天是几号？", sampleEnglish: "What is the date today?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "喝", pinyin: "hē", english: "to drink", sampleChinese: "你想喝点什么？", sampleEnglish: "What would you like to drink?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "和", pinyin: "hé", english: "and", sampleChinese: "我喜欢咖啡和茶。", sampleEnglish: "I like coffee and tea.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "很", pinyin: "hěn", english: "very", sampleChinese: "他是一个很好的朋友。", sampleEnglish: "He is a very good friend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "后", pinyin: "hòu", english: "after", sampleChinese: "晚饭后，我喜欢散步。", sampleEnglish: "After dinner, I like to take a walk.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "后边", pinyin: "hòubiān", english: "behind", sampleChinese: "请站在我后边。", sampleEnglish: "Please stand behind me.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "后天", pinyin: "hòutiān", english: "the day after tomorrow", sampleChinese: "我们后天去旅行。", sampleEnglish: "We're going on a trip the day after tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "花", pinyin: "huā", english: "flower", sampleChinese: "这朵花美丽。", sampleEnglish: "This flower is beautiful.", rightInARow: 0, nextReviewDate: Date.now() },    
    { chinese: "话", pinyin: "huà", english: "talk", sampleChinese: "我们聊聊吧。", sampleEnglish: "Let's talk.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "坏", pinyin: "huài", english: "bad", sampleChinese: "这个电池坏了。", sampleEnglish: "This battery is bad.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "还", pinyin: "hái", english: "still", sampleChinese: "我还在等你。", sampleEnglish: "I'm still waiting for you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回", pinyin: "huí", english: "return", sampleChinese: "我马上回来。", sampleEnglish: "I'll be right back.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回答", pinyin: "huídá", english: "answer", sampleChinese: "请回答这个问题。", sampleEnglish: "Please answer this question.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回到", pinyin: "huídào", english: "return to", sampleChinese: "他回到故乡。", sampleEnglish: "He returned to his hometown.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回家", pinyin: "huíjiā", english: "go home", sampleChinese: "我渴望回家。", sampleEnglish: "I long to go home.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回来", pinyin: "huílái", english: "come back", sampleChinese: "他答应很快回来。", sampleEnglish: "He promised to come back soon.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回去", pinyin: "huíqù", english: "go back", sampleChinese: "现在是时候回去了。", sampleEnglish: "It's time to go back now.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "会", pinyin: "huì", english: "will", sampleChinese: "明天会晴朗。", sampleEnglish: "Tomorrow will be sunny.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "火车", pinyin: "huǒchē", english: "train", sampleChinese: "我喜欢坐火车。", sampleEnglish: "I like taking the train.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "机场", pinyin: "jīchǎng", english: "airport", sampleChinese: "机场繁忙。", sampleEnglish: "The airport is busy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "机票", pinyin: "jīpiào", english: "plane ticket", sampleChinese: "我已预订机票。", sampleEnglish: "I've booked the plane ticket.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "鸡蛋", pinyin: "jīdàn", english: "egg", sampleChinese: "我要煮鸡蛋。", sampleEnglish: "I want to cook eggs.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "几", pinyin: "jǐ", english: "how many", sampleChinese: "你几点来？", sampleEnglish: "What time will you come?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "记", pinyin: "jì", english: "to record", sampleChinese: "请记下这个电话号码。", sampleEnglish: "Please record this phone number.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "记得", pinyin: "jìde", english: "to remember", sampleChinese: "我记得你的名字。", sampleEnglish: "I remember your name.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "记住", pinyin: "jìzhù", english: "to memorize", sampleChinese: "你要记住这些单词。", sampleEnglish: "You should memorize these words.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "家", pinyin: "jiā", english: "home", sampleChinese: "我在家里。", sampleEnglish: "I am at home.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "家里", pinyin: "jiālǐ", english: "at home", sampleChinese: "爸爸在家里。", sampleEnglish: "Dad is at home.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "家人", pinyin: "jiārén", english: "family member", sampleChinese: "我的家人很亲切。", sampleEnglish: "My family members are very kind.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "间", pinyin: "jiān", english: "room", sampleChinese: "这是我的卧室。", sampleEnglish: "This is my bedroom.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "见", pinyin: "jiàn", english: "to see", sampleChinese: "我想见你。", sampleEnglish: "I want to see you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "见面", pinyin: "jiànmiàn", english: "to meet", sampleChinese: "我们明天见面。", sampleEnglish: "We'll meet tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "教", pinyin: "jiāo", english: "to teach", sampleChinese: "老师教我们汉字。", sampleEnglish: "The teacher teaches us Chinese characters.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "叫", pinyin: "jiào", english: "to call", sampleChinese: "请叫我一声老师。", sampleEnglish: "Please call me 'teacher'.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "教学楼", pinyin: "jiàoxué lóu", english: "teaching building", sampleChinese: "教学楼在前面。", sampleEnglish: "The teaching building is in front.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "姐姐", pinyin: "jiějiě", english: "older sister", sampleChinese: "我有一个姐姐。", sampleEnglish: "I have an older sister.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "介绍", pinyin: "jièshào", english: "to introduce", sampleChinese: "请介绍一下你自己。", sampleEnglish: "Please introduce yourself.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "今年", pinyin: "jīnnián", english: "this year", sampleChinese: "今年是兔年。", sampleEnglish: "This year is the Year of the Rabbit.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "今天", pinyin: "jīntiān", english: "today", sampleChinese: "今天天气很好。", sampleEnglish: "The weather is nice today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "进", pinyin: "jìn", english: "to enter", sampleChinese: "请进来。", sampleEnglish: "Please come in.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "进来", pinyin: "jìn lái", english: "to come in", sampleChinese: "你可以进来吗？", sampleEnglish: "Can you come in?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "进去", pinyin: "jìnqù", english: "to go in", sampleChinese: "他要进去一下。", sampleEnglish: "He's going in for a moment.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "九", pinyin: "jiǔ", english: "nine", sampleChinese: "九是一个幸运数字。", sampleEnglish: "Nine is a lucky number.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "就", pinyin: "jiù", english: "just", sampleChinese: "我就来了。", sampleEnglish: "I just arrived.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "觉得", pinyin: "juéde", english: "to feel", sampleChinese: "我觉得很高兴。", sampleEnglish: "I feel very happy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "开", pinyin: "kāi", english: "to open", sampleChinese: "请开门。", sampleEnglish: "Please open the door.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "开车", pinyin: "kāichē", english: "to drive", sampleChinese: "他会开车。", sampleEnglish: "He can drive.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "开会", pinyin: "kāihuì", english: "to have a meeting", sampleChinese: "他们明天要开会。", sampleEnglish: "They are going to have a meeting tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "开玩笑", pinyin: "kāi wánxiào", english: "to joke", sampleChinese: "他在开玩笑吗？", sampleEnglish: "Is he joking?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "看", pinyin: "kàn", english: "to look at", sampleChinese: "我想看这本书。", sampleEnglish: "I want to look at this book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "看病", pinyin: "kànbìng", english: "to see a doctor", sampleChinese: "他生病了，需要看病。", sampleEnglish: "He is sick and needs to see a doctor.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "看到", pinyin: "kàndào", english: "to see", sampleChinese: "我看到了你的消息。", sampleEnglish: "I saw your message.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "看见", pinyin: "kànjiàn", english: "to see", sampleChinese: "我看见了一只小狗。", sampleEnglish: "I saw a little dog.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "考", pinyin: "kǎo", english: "to take an exam", sampleChinese: "明天我要考数学考试。", sampleEnglish: "I have a math exam tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "考试", pinyin: "kǎoshì", english: "exam", sampleChinese: "期末考试很重要。", sampleEnglish: "Final exams are important.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "渴", pinyin: "kě", english: "thirsty", sampleChinese: "我很渴，想喝水。", sampleEnglish: "I'm very thirsty and want to drink water.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "课", pinyin: "kè", english: "class", sampleChinese: "我今天有汉语课。", sampleEnglish: "I have Chinese class today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "课本", pinyin: "kèběn", english: "textbook", sampleChinese: "我的课本在书包里。", sampleEnglish: "My textbook is in my backpack.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "课文", pinyin: "kèwén", english: "text of a lesson", sampleChinese: "我们要读这篇课文。", sampleEnglish: "We have to read this lesson's text.", rightInARow: 0, nextReviewDate: Date.now() },    
    { chinese: "口", pinyin: "kǒu", english: "mouth", sampleChinese: "用你的口说话。", sampleEnglish: "Speak with your mouth.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "块", pinyin: "kuài", english: "piece", sampleChinese: "这块蛋糕很好吃。", sampleEnglish: "This piece of cake is delicious.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "快", pinyin: "kuài", english: "fast", sampleChinese: "他跑得很快。", sampleEnglish: "He runs very fast.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "来", pinyin: "lái", english: "to come", sampleChinese: "我明天来。", sampleEnglish: "I'll come tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "来到", pinyin: "lái dào", english: "to arrive", sampleChinese: "他已经来到了机场。", sampleEnglish: "He has already arrived at the airport.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "老", pinyin: "lǎo", english: "old", sampleChinese: "这辆车很老了。", sampleEnglish: "This car is very old.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "老人", pinyin: "lǎo rén", english: "old person", sampleChinese: "老人们喜欢在公园散步。", sampleEnglish: "Old people like to take walks in the park.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "老师", pinyin: "lǎo shī", english: "teacher", sampleChinese: "我的老师很聪明。", sampleEnglish: "My teacher is very smart.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "了", pinyin: "le", english: "particle for past tense", sampleChinese: "我吃了晚饭。", sampleEnglish: "I ate dinner.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "累", pinyin: "lèi", english: "tired", sampleChinese: "他工作一整天，现在很累。", sampleEnglish: "He worked all day and is very tired.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "冷", pinyin: "lěng", english: "cold", sampleChinese: "今天天气很冷。", sampleEnglish: "The weather is very cold today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "里", pinyin: "lǐ", english: "inside", sampleChinese: "手机在包里。", sampleEnglish: "The phone is inside the bag.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "里边", pinyin: "lǐ biān", english: "inside", sampleChinese: "请把东西放在盒子里边。", sampleEnglish: "Please put the things inside the box.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "两", pinyin: "liǎng", english: "two", sampleChinese: "我有两个弟弟。", sampleEnglish: "I have two younger brothers.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "零", pinyin: "líng", english: "zero", sampleChinese: "这个数字是零。", sampleEnglish: "This number is zero.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "六", pinyin: "liù", english: "six", sampleChinese: "六只猫在院子里。", sampleEnglish: "There are six cats in the yard.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "楼", pinyin: "lóu", english: "floor", sampleChinese: "我住在第五楼。", sampleEnglish: "I live on the fifth floor.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "楼上", pinyin: "lóu shàng", english: "upstairs", sampleChinese: "厕所在楼上。", sampleEnglish: "The restroom is upstairs.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "楼下", pinyin: "lóu xià", english: "downstairs", sampleChinese: "他在楼下等你。", sampleEnglish: "He's waiting for you downstairs.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "路", pinyin: "lù", english: "road", sampleChinese: "这条路很宽。", sampleEnglish: "This road is very wide.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "路口", pinyin: "lù kǒu", english: "intersection", sampleChinese: "在路口左转。", sampleEnglish: "Turn left at the intersection.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "路上", pinyin: "lù shàng", english: "on the road", sampleChinese: "路上有很多车。", sampleEnglish: "There are a lot of cars on the road.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "妈妈", pinyin: "mā ma", english: "mom", sampleChinese: "我的妈妈很疼爱我。", sampleEnglish: "My mom loves me very much.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "马路", pinyin: "mǎ lù", english: "road, street", sampleChinese: "过马路要小心。", sampleEnglish: "Be careful when crossing the street.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "马上", pinyin: "mǎ shàng", english: "immediately", sampleChinese: "我马上回来。", sampleEnglish: "I'll be back immediately.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "吗", pinyin: "ma", english: "question particle", sampleChinese: "你好吗？", sampleEnglish: "How are you?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "买", pinyin: "mǎi", english: "to buy", sampleChinese: "我要去买东西。", sampleEnglish: "I'm going to buy some things.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "慢", pinyin: "màn", english: "slow", sampleChinese: "他跑得很慢。", sampleEnglish: "He runs very slowly.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "忙", pinyin: "máng", english: "busy", sampleChinese: "我很忙，没时间。", sampleEnglish: "I'm busy and don't have time.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "毛", pinyin: "máo", english: "fur, hair", sampleChinese: "这只猫的毛很软。", sampleEnglish: "This cat's fur is very soft.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "没", pinyin: "méi", english: "not", sampleChinese: "我没吃饭。", sampleEnglish: "I haven't eaten.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "没关系", pinyin: "méi guān xì", english: "it's okay", sampleChinese: "没关系，我们可以再试一次。", sampleEnglish: "It's okay, we can try again.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "没什么", pinyin: "méi shén me", english: "it's nothing", sampleChinese: "没什么，别担心。", sampleEnglish: "It's nothing, don't worry.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "没事儿", pinyin: "méi shì er", english: "it's okay", sampleChinese: "我没事儿，谢谢。", sampleEnglish: "I'm okay, thanks.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "没有", pinyin: "méi yǒu", english: "not have", sampleChinese: "他没有手机。", sampleEnglish: "He doesn't have a phone.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "妹妹", pinyin: "mèi mei", english: "sister", sampleChinese: "我的妹妹很可爱。", sampleEnglish: "My sister is very cute.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "门", pinyin: "mén", english: "door", sampleChinese: "请关上门。", sampleEnglish: "Please close the door.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "门口", pinyin: "mén kǒu", english: "doorway", sampleChinese: "他站在门口等你。", sampleEnglish: "He's standing in the doorway waiting for you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "门票", pinyin: "mén piào", english: "entrance ticket", sampleChinese: "门票多少钱？", sampleEnglish: "How much is the entrance ticket?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "们", pinyin: "men", english: "plural marker", sampleChinese: "我们是好朋友。", sampleEnglish: "We are good friends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "米饭", pinyin: "mǐ fàn", english: "rice", sampleChinese: "我喜欢吃米饭。", sampleEnglish: "I like to eat rice.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "面包", pinyin: "miàn bāo", english: "bread", sampleChinese: "早餐吃面包很常见。", sampleEnglish: "Eating bread for breakfast is common.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "面条儿", pinyin: "miàn tiáo er", english: "noodles", sampleChinese: "面条儿很好吃。", sampleEnglish: "Noodles are very delicious.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "名字", pinyin: "míng zì", english: "name", sampleChinese: "你叫什么名字？", sampleEnglish: "What's your name?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "明白", pinyin: "míng bai", english: "to understand", sampleChinese: "我明白了你的意思。", sampleEnglish: "I understand what you mean.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "明年", pinyin: "míng nián", english: "next year", sampleChinese: "明年我要去旅行。", sampleEnglish: "I'm going to travel next year.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "明天", pinyin: "míng tiān", english: "tomorrow", sampleChinese: "明天是周末。", sampleEnglish: "Tomorrow is the weekend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "拿", pinyin: "ná", english: "to take, to hold", sampleChinese: "请拿给我。", sampleEnglish: "Please hand it to me.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "哪", pinyin: "nǎ", english: "where", sampleChinese: "哪个是你的书？", sampleEnglish: "Which one is your book?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "哪里", pinyin: "nǎ lǐ", english: "where", sampleChinese: "你住在哪里？", sampleEnglish: "Where do you live?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "哪儿", pinyin: "nǎ er", english: "where", sampleChinese: "你去哪儿？", sampleEnglish: "Where are you going?", rightInARow: 0, nextReviewDate: Date.now() },    
    { chinese: "哪些", pinyin: "nǎ xiē", english: "which", sampleChinese: "你喜欢哪些水果？", sampleEnglish: "Which fruits do you like?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "那", pinyin: "nà", english: "that", sampleChinese: "那是我的书。", sampleEnglish: "That is my book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "那边", pinyin: "nà biān", english: "there", sampleChinese: "她在那边等你。", sampleEnglish: "She's waiting for you over there.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "那里", pinyin: "nà lǐ", english: "there", sampleChinese: "那里有一家好饭馆。", sampleEnglish: "There's a good restaurant over there.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "那儿", pinyin: "nà er", english: "there", sampleChinese: "我们去那儿玩。", sampleEnglish: "Let's go play there.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "那些", pinyin: "nà xiē", english: "those", sampleChinese: "那些书是我的。", sampleEnglish: "Those books are mine.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "奶", pinyin: "nǎi", english: "milk", sampleChinese: "我要一杯奶。", sampleEnglish: "I'd like a glass of milk.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "奶奶", pinyin: "nǎi nai", english: "grandmother", sampleChinese: "我的奶奶很慈祥。", sampleEnglish: "My grandmother is very kind.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "男", pinyin: "nán", english: "male", sampleChinese: "男人和女人。", sampleEnglish: "Men and women.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "男孩儿", pinyin: "nán hái er", english: "boy", sampleChinese: "这是一个聪明的男孩儿。", sampleEnglish: "This is a clever boy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "男朋友", pinyin: "nán péng you", english: "boyfriend", sampleChinese: "她的男朋友很帅。", sampleEnglish: "Her boyfriend is handsome.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "男人", pinyin: "nán rén", english: "man", sampleChinese: "这位男人是医生。", sampleEnglish: "This man is a doctor.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "男生", pinyin: "nán shēng", english: "male student", sampleChinese: "男生和女生都来参加。", sampleEnglish: "Both male and female students are coming to participate.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "南", pinyin: "nán", english: "south", sampleChinese: "南边有一座山。", sampleEnglish: "There's a mountain to the south.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "南边", pinyin: "nán biān", english: "south", sampleChinese: "我的家在南边。", sampleEnglish: "My home is in the south.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "难", pinyin: "nán", english: "difficult", sampleChinese: "这个问题很难。", sampleEnglish: "This question is difficult.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "呢", pinyin: "ne", english: "question particle", sampleChinese: "你呢？", sampleEnglish: "What about you?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "能", pinyin: "néng", english: "can", sampleChinese: "我能帮助你。", sampleEnglish: "I can help you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "你", pinyin: "nǐ", english: "you", sampleChinese: "你好吗？", sampleEnglish: "How are you?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "你们", pinyin: "nǐ men", english: "you all", sampleChinese: "你们都是我的朋友。", sampleEnglish: "You all are my friends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "年", pinyin: "nián", english: "year", sampleChinese: "明年是新的一年。", sampleEnglish: "Next year is a new year.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "您", pinyin: "nín", english: "you (polite)", sampleChinese: "您的座位在哪里？", sampleEnglish: "Where is your seat?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "牛奶", pinyin: "niú nǎi", english: "milk", sampleChinese: "牛奶是健康的。", sampleEnglish: "Milk is healthy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女", pinyin: "nǚ", english: "female", sampleChinese: "男女平等。", sampleEnglish: "Gender equality.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女儿", pinyin: "nǚ ér", english: "daughter", sampleChinese: "她是我的女儿。", sampleEnglish: "She is my daughter.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女孩儿", pinyin: "nǚ hái er", english: "girl", sampleChinese: "那是一个聪明的女孩儿。", sampleEnglish: "That's a clever girl.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女朋友", pinyin: "nǚ péng you", english: "girlfriend", sampleChinese: "她的女朋友很漂亮。", sampleEnglish: "Her girlfriend is pretty.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女人", pinyin: "nǚ rén", english: "woman", sampleChinese: "女人和男人。", sampleEnglish: "Women and men.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女生", pinyin: "nǚ shēng", english: "female student", sampleChinese: "女生都非常用功。", sampleEnglish: "Female students are all very hardworking.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "旁边", pinyin: "páng biān", english: "beside", sampleChinese: "书在桌子旁边。", sampleEnglish: "The book is beside the table.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "跑", pinyin: "pǎo", english: "to run", sampleChinese: "他喜欢跑步。", sampleEnglish: "He likes to run.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "朋友", pinyin: "péng you", english: "friend", sampleChinese: "朋友们一起玩。", sampleEnglish: "Friends play together.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "票", pinyin: "piào", english: "ticket", sampleChinese: "我要买电影票。", sampleEnglish: "I want to buy movie tickets.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "七", pinyin: "qī", english: "seven", sampleChinese: "七天一周。", sampleEnglish: "Seven days in a week.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "起", pinyin: "qǐ", english: "to rise", sampleChinese: "太阳已经起来了。", sampleEnglish: "The sun has risen.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "起床", pinyin: "qǐ chuáng", english: "to get up", sampleChinese: "早上你什么时候起床？", sampleEnglish: "What time do you get up in the morning?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "起来", pinyin: "qǐ lái", english: "to stand up", sampleChinese: "请大家都站起来。", sampleEnglish: "Please everyone stand up.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "汽车", pinyin: "qì chē", english: "car", sampleChinese: "这是我的汽车。", sampleEnglish: "This is my car.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "前", pinyin: "qián", english: "front", sampleChinese: "请坐在前面。", sampleEnglish: "Please sit in the front.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "前边", pinyin: "qián biān", english: "in front", sampleChinese: "餐厅在房间的前边。", sampleEnglish: "The dining room is in front of the room.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "前天", pinyin: "qián tiān", english: "the day before yesterday", sampleChinese: "前天我去了图书馆。", sampleEnglish: "I went to the library the day before yesterday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "钱", pinyin: "qián", english: "money", sampleChinese: "这是我的钱包。", sampleEnglish: "This is my wallet.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "钱包", pinyin: "qián bāo", english: "wallet", sampleChinese: "我丢了我的钱包。", sampleEnglish: "I lost my wallet.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "请", pinyin: "qǐng", english: "please", sampleChinese: "请坐下。", sampleEnglish: "Please have a seat.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "请假", pinyin: "qǐng jià", english: "to ask for leave", sampleChinese: "他因病请假。", sampleEnglish: "He asked for leave due to illness.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "请进", pinyin: "qǐng jìn", english: "please come in", sampleChinese: "请进，别客气。", sampleEnglish: "Please come in, don't be shy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "请问", pinyin: "qǐng wèn", english: "please ask", sampleChinese: "请问这里有餐厅吗？", sampleEnglish: "May I ask if there is a restaurant here?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "请坐", pinyin: "qǐng zuò", english: "please sit", sampleChinese: "请坐下，别拘谨。", sampleEnglish: "Please sit down, don't be formal.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "球", pinyin: "qiú", english: "ball", sampleChinese: "我们去打篮球吧。", sampleEnglish: "Let's go play basketball.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "去", pinyin: "qù", english: "go", sampleChinese: "我要去商店。", sampleEnglish: "I want to go to the store.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "去年", pinyin: "qù nián", english: "last year", sampleChinese: "去年的生日派对很开心。", sampleEnglish: "Last year's birthday party was fun.", rightInARow: 0, nextReviewDate: Date.now() },    
    { chinese: "热", english: "hot", sampleChinese: "今天很热。", sampleEnglish: "It's very hot today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "人", pinyin: "rén", english: "person", sampleChinese: "这是我的朋友，他是个好人。", sampleEnglish: "This is my friend; he's a good person.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "认识", pinyin: "rèn shi", english: "to know", sampleChinese: "你认识这位老师吗？", sampleEnglish: "Do you know this teacher?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "认真", pinyin: "rèn zhēn", english: "serious", sampleChinese: "他对工作非常认真。", sampleEnglish: "He is very serious about his work.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "日", pinyin: "rì", english: "day", sampleChinese: "今天是星期一，明天是星期二。", sampleEnglish: "Today is Monday, and tomorrow is Tuesday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "日期", pinyin: "rì qī", english: "date", sampleChinese: "请告诉我今天的日期。", sampleEnglish: "Please tell me today's date.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "肉", pinyin: "ròu", english: "meat", sampleChinese: "我喜欢吃牛肉。", sampleEnglish: "I like to eat beef.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "三", pinyin: "sān", english: "three", sampleChinese: "三只小猫在玩耍。", sampleEnglish: "Three kittens are playing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "山", pinyin: "shān", english: "mountain", sampleChinese: "那座山非常高。", sampleEnglish: "That mountain is very high.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "商场", pinyin: "shāng chǎng", english: "shopping mall", sampleChinese: "周末我们去商场购物。", sampleEnglish: "We go shopping at the mall on weekends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "商店", pinyin: "shāng diàn", english: "store", sampleChinese: "这家商店有很多衣服。", sampleEnglish: "This store has a lot of clothes.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上", pinyin: "shàng", english: "above", sampleChinese: "请把杯子放在桌子上。", sampleEnglish: "Please put the cup on the table.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上班", pinyin: "shàng bān", english: "go to work", sampleChinese: "他每天早上七点上班。", sampleEnglish: "He goes to work at 7 AM every morning.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上边", pinyin: "shàng biān", english: "above", sampleChinese: "飞机在云层上边飞行。", sampleEnglish: "The plane is flying above the clouds.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上车", pinyin: "shàng chē", english: "get on the car", sampleChinese: "快上车，我们要出发了。", sampleEnglish: "Hurry up and get on the car; we're about to leave.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上次", pinyin: "shàng cì", english: "last time", sampleChinese: "上次去海滩是在去年。", sampleEnglish: "The last time I went to the beach was last year.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上课", pinyin: "shàng kè", english: "attend a class", sampleChinese: "我们明天上课。", sampleEnglish: "We have class tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上网", pinyin: "shàng wǎng", english: "go online", sampleChinese: "晚上我喜欢上网冲浪。", sampleEnglish: "I like to go online surfing at night.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上午", pinyin: "shàng wǔ", english: "morning", sampleChinese: "上午十点是开会时间。", sampleEnglish: "The meeting is at 10 AM in the morning.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上学", pinyin: "shàng xué", english: "go to school", sampleChinese: "孩子们都喜欢上学。", sampleEnglish: "Children all like to go to school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "少", pinyin: "shǎo", english: "few", sampleChinese: "这个城市的人口很少。", sampleEnglish: "The population of this city is very small.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "谁", pinyin: "shéi", english: "who", sampleChinese: "谁来过这里？", sampleEnglish: "Who has been here?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "身上", pinyin: "shēn shàng", english: "on one's body", sampleChinese: "我的钥匙在我的包里或者身上。", sampleEnglish: "My keys are in my bag or on my body.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "身体", pinyin: "shēn tǐ", english: "body", sampleChinese: "保持身体健康很重要。", sampleEnglish: "It's important to keep your body healthy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "什么", pinyin: "shén me", english: "what", sampleChinese: "你在想什么？", sampleEnglish: "What are you thinking about?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "生病", pinyin: "shēng bìng", english: "get sick", sampleChinese: "他生病了，不能去上学。", sampleEnglish: "He's sick and can't go to school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "生气", pinyin: "shēng qì", english: "get angry", sampleChinese: "不要生气，事情会好起来的。", sampleEnglish: "Don't get angry; things will get better.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "生日", pinyin: "shēng rì", english: "birthday", sampleChinese: "今天是我的生日。", sampleEnglish: "Today is my birthday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "十", pinyin: "shí", english: "ten", sampleChinese: "这是十块钱。", sampleEnglish: "This is ten dollars.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "时候", pinyin: "shí hou", english: "time", sampleChinese: "晚上是一个看电影的好时候。", sampleEnglish: "Evening is a good time to watch a movie.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "时间", pinyin: "shí jiān", english: "time", sampleChinese: "我没有足够的时间去购物。", sampleEnglish: "I don't have enough time to go shopping.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "事", pinyin: "shì", english: "thing", sampleChinese: "这是一件好事。", sampleEnglish: "This is a good thing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "试", pinyin: "shì", english: "try", sampleChinese: "不要害怕尝试新东西。", sampleEnglish: "Don't be afraid to try new things.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "是", pinyin: "shì", english: "is", sampleChinese: "这是我的手机。", sampleEnglish: "This is my phone.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "是不是", pinyin: "shì bu shì", english: "whether or not", sampleChinese: "你确定是不是这个答案？", sampleEnglish: "Are you sure whether this is the answer or not?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "手", pinyin: "shǒu", english: "hand", sampleChinese: "请把东西放在我手里。", sampleEnglish: "Please put the thing in my hand.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "手机", pinyin: "shǒu jī", english: "mobile phone", sampleChinese: "我把手机落在家里了。", sampleEnglish: "I left my mobile phone at home.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "书", pinyin: "shū", english: "book", sampleChinese: "我喜欢读书。", sampleEnglish: "I like reading books.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "书包", pinyin: "shū bāo", english: "school bag", sampleChinese: "我需要一个新书包。", sampleEnglish: "I need a new school bag.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "书店", pinyin: "shū diàn", english: "bookstore", sampleChinese: "我经常去书店购买书。", sampleEnglish: "I often go to the bookstore to buy books.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "树", pinyin: "shù", english: "tree", sampleChinese: "公园里有很多漂亮的树。", sampleEnglish: "There are many beautiful trees in the park.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "水", pinyin: "shuǐ", english: "water", sampleChinese: "水是生命之源。", sampleEnglish: "Water is the source of life.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "水果", pinyin: "shuǐ guǒ", english: "fruit", sampleChinese: "我早餐吃了一些水果。", sampleEnglish: "I had some fruit for breakfast.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "睡", pinyin: "shuì", english: "sleep", sampleChinese: "晚上好，我去睡觉了。", sampleEnglish: "Good night, I'm going to sleep.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "睡觉", pinyin: "shuì jiào", english: "go to sleep", sampleChinese: "晚上好，该睡觉了。", sampleEnglish: "Good evening, it's time to go to sleep.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "说", pinyin: "shuō", english: "say", sampleChinese: "你想对我说什么？", sampleEnglish: "What do you want to say to me?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "说话", pinyin: "shuō huà", english: "speak", sampleChinese: "请不要在课堂上说话。", sampleEnglish: "Please don't speak in the classroom.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "四", pinyin: "sì", english: "four", sampleChinese: "有四个季节。", sampleEnglish: "There are four seasons.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "送", pinyin: "sòng", english: "give", sampleChinese: "他送了一份礼物给她。", sampleEnglish: "He gave her a gift.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "岁", pinyin: "suì", english: "years old", sampleChinese: "她五岁了。", sampleEnglish: "She is five years old.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "他", pinyin: "tā", english: "he", sampleChinese: "他是我的朋友。", sampleEnglish: "He is my friend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "他们", pinyin: "tā men", english: "they", sampleChinese: "他们正在学习中文。", sampleEnglish: "They are learning Chinese.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "她", pinyin: "tā", english: "she", sampleChinese: "她非常聪明。", sampleEnglish: "She is very smart.", rightInARow: 0, nextReviewDate: Date.now() },    
    { chinese: "她们", english: "they (feminine)", sampleChinese: "她们是好朋友。", sampleEnglish: "They are good friends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "太", pinyin: "tài", english: "too", sampleChinese: "这个苹果太甜了。", sampleEnglish: "This apple is too sweet.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "天", pinyin: "tiān", english: "day", sampleChinese: "今天是晴天。", sampleEnglish: "Today is a sunny day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "天气", pinyin: "tiān qì", english: "weather", sampleChinese: "天气预报说明天会下雨。", sampleEnglish: "The weather forecast says it will rain tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "听", pinyin: "tīng", english: "listen", sampleChinese: "请安静地听老师讲课。", sampleEnglish: "Please listen quietly to the teacher's lecture.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "听到", pinyin: "tīng dào", english: "hear", sampleChinese: "我听到了她的歌声。", sampleEnglish: "I heard her singing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "听见", pinyin: "tīng jiàn", english: "hear", sampleChinese: "我听见了一声巨响。", sampleEnglish: "I heard a loud noise.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "听写", pinyin: "tīng xiě", english: "dictation", sampleChinese: "明天我们要做听写练习。", sampleEnglish: "We will do a dictation exercise tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "同学", pinyin: "tóng xué", english: "classmate", sampleChinese: "我的同学都很友好。", sampleEnglish: "My classmates are all very friendly.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "图书馆", pinyin: "tú shū guǎn", english: "library", sampleChinese: "图书馆是学习的好地方。", sampleEnglish: "The library is a good place to study.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "外", pinyin: "wài", english: "outside", sampleChinese: "外面下雨了。", sampleEnglish: "It's raining outside.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "外边", pinyin: "wài biān", english: "outside", sampleChinese: "请在外边等一下。", sampleEnglish: "Please wait outside for a moment.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "外国", pinyin: "wài guó", english: "foreign country", sampleChinese: "我想去外国旅行。", sampleEnglish: "I want to travel to a foreign country.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "外语", pinyin: "wài yǔ", english: "foreign language", sampleChinese: "学习外语需要耐心。", sampleEnglish: "Learning a foreign language requires patience.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "玩儿", pinyin: "wánr", english: "play", sampleChinese: "孩子们在公园里玩得很开心。", sampleEnglish: "The kids are playing happily in the park.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "晚", pinyin: "wǎn", english: "late", sampleChinese: "我会回家很晚。", sampleEnglish: "I will go home late.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "晚饭", pinyin: "wǎn fàn", english: "dinner", sampleChinese: "晚饭后我们去看电影。", sampleEnglish: "We'll go to the movies after dinner.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "晚上", pinyin: "wǎn shàng", english: "evening", sampleChinese: "我喜欢在晚上散步。", sampleEnglish: "I like to take a walk in the evening.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "网上", pinyin: "wǎng shàng", english: "online", sampleChinese: "你可以在网上购物。", sampleEnglish: "You can shop online.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "网友", pinyin: "wǎng yǒu", english: "online friend", sampleChinese: "我认识了很多网友。", sampleEnglish: "I've made many online friends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "忘", pinyin: "wàng", english: "forget", sampleChinese: "不要忘了明天的约会。", sampleEnglish: "Don't forget our meeting tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "忘记", pinyin: "wàng jì", english: "forget", sampleChinese: "我忘记了那个密码。", sampleEnglish: "I forgot that password.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "问", pinyin: "wèn", english: "ask", sampleChinese: "如果有问题，就问老师。", sampleEnglish: "If you have questions, ask the teacher.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "我", pinyin: "wǒ", english: "I, me", sampleChinese: "我喜欢学习新东西。", sampleEnglish: "I enjoy learning new things.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "我们", pinyin: "wǒ men", english: "we, us", sampleChinese: "我们一起庆祝生日。", sampleEnglish: "We celebrate birthdays together.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "五", pinyin: "wǔ", english: "five", sampleChinese: "五个苹果。", sampleEnglish: "Five apples.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "午饭", pinyin: "wǔ fàn", english: "lunch", sampleChinese: "午饭时间到了。", sampleEnglish: "It's lunchtime.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "西", pinyin: "xī", english: "west", sampleChinese: "太阳在西边落山。", sampleEnglish: "The sun sets in the west.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "西边", pinyin: "xī biān", english: "west", sampleChinese: "我家在城市的西边。", sampleEnglish: "My house is on the west side of the city.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "洗", pinyin: "xǐ", english: "wash", sampleChinese: "我要洗衣服了。", sampleEnglish: "I need to wash the clothes.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "洗手间", pinyin: "xǐ shǒu jiān", english: "bathroom", sampleChinese: "洗手间在房间的尽头。", sampleEnglish: "The bathroom is at the end of the hallway.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "喜欢", pinyin: "xǐ huān", english: "like", sampleChinese: "我喜欢吃冰淇淋。", sampleEnglish: "I like to eat ice cream.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下", pinyin: "xià", english: "below", sampleChinese: "请看下面的表格。", sampleEnglish: "Please check the table below.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下班", pinyin: "xià bān", english: "get off work", sampleChinese: "他每天下午五点下班。", sampleEnglish: "He gets off work at 5 PM every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下边", pinyin: "xià biān", english: "below", sampleChinese: "画在下边的是山。", sampleEnglish: "The mountains are drawn below.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下车", pinyin: "xià chē", english: "get off the car", sampleChinese: "我们现在可以下车了。", sampleEnglish: "We can get off the car now.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下次", pinyin: "xià cì", english: "next time", sampleChinese: "下次再见！", sampleEnglish: "See you next time!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下课", pinyin: "xià kè", english: "finish class", sampleChinese: "下课后，我们一起去吃饭。", sampleEnglish: "Let's have dinner together after class.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下午", pinyin: "xià wǔ", english: "afternoon", sampleChinese: "我下午要开会。", sampleEnglish: "I have a meeting in the afternoon.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下雨", pinyin: "xià yǔ", english: "rain", sampleChinese: "明天会下雨。", sampleEnglish: "It will rain tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "先", pinyin: "xiān", english: "first", sampleChinese: "请你先坐下。", sampleEnglish: "Please have a seat first.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "先生", pinyin: "xiān shēng", english: "mister", sampleChinese: "这位先生需要帮助。", sampleEnglish: "Mister, do you need assistance?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "现在", pinyin: "xiàn zài", english: "now", sampleChinese: "我们现在开始。", sampleEnglish: "We start now.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "想", pinyin: "xiǎng", english: "think, want", sampleChinese: "我想吃冰淇淋。", sampleEnglish: "I want to eat ice cream.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小", pinyin: "xiǎo", english: "small", sampleChinese: "这是一个小狗。", sampleEnglish: "This is a small dog.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小孩儿", pinyin: "xiǎo hái ér", english: "child", sampleChinese: "小孩儿们在公园玩得很开心。", sampleEnglish: "The children are playing happily in the park.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小姐", pinyin: "xiǎo jiě", english: "miss, young lady", sampleChinese: "这位小姐在等出租车。", sampleEnglish: "The young lady is waiting for a taxi.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小朋友", pinyin: "xiǎo péng yǒu", english: "child", sampleChinese: "小朋友们都在学校。", sampleEnglish: "The children are all at school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小时", pinyin: "xiǎo shí", english: "hour", sampleChinese: "我每天锻炼半小时。", sampleEnglish: "I exercise for half an hour every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小学", pinyin: "xiǎo xué", english: "elementary school", sampleChinese: "小学生学习基础知识。", sampleEnglish: "Elementary school students learn fundamental knowledge.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小学生", pinyin: "xiǎo xué shēng", english: "elementary school student", sampleChinese: "这位小学生很聪明。", sampleEnglish: "This elementary school student is very smart.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "笑", pinyin: "xiào", english: "laugh", sampleChinese: "他的笑声很响亮。", sampleEnglish: "His laughter is very loud.", rightInARow: 0, nextReviewDate: Date.now() },    
    { chinese: "写", pinyin: "xiě", english: "write", sampleChinese: "请写下你的名字。", sampleEnglish: "Please write your name.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "谢谢", pinyin: "xiè xiè", english: "thank you", sampleChinese: "谢谢你的帮助。", sampleEnglish: "Thank you for your help.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "新", pinyin: "xīn", english: "new", sampleChinese: "新一年开始了。", sampleEnglish: "The new year has begun.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "新年", pinyin: "xīn nián", english: "New Year", sampleChinese: "新年快乐！祝你幸福安康。", sampleEnglish: "Happy New Year! Wishing you happiness and good health.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "星期", pinyin: "xīng qī", english: "week", sampleChinese: "星期几是周末？", sampleEnglish: "Which day of the week is the weekend?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "星期日", pinyin: "xīng qī rì", english: "Sunday", sampleChinese: "星期日是我休息的日子。", sampleEnglish: "Sunday is my day off.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "星期天", pinyin: "xīng qī tiān", english: "Sunday", sampleChinese: "星期天我们去公园。", sampleEnglish: "We're going to the park on Sunday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "行", pinyin: "xíng", english: "go", sampleChinese: "走吧，我们准备好了。", sampleEnglish: "Let's go; we're ready.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "休息", pinyin: "xiū xí", english: "rest", sampleChinese: "周末我通常休息一下。", sampleEnglish: "I usually rest a bit on the weekends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "学", pinyin: "xué", english: "study", sampleChinese: "我喜欢学新东西。", sampleEnglish: "I like to study new things.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "学生", pinyin: "xué shēng", english: "student", sampleChinese: "学生们在图书馆学习。", sampleEnglish: "Students are studying in the library.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "学习", pinyin: "xué xí", english: "learn, study", sampleChinese: "学习是一辈子的事情。", sampleEnglish: "Learning is a lifelong endeavor.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "学校", pinyin: "xué xiào", english: "school", sampleChinese: "我去的学校离家很远。", sampleEnglish: "The school I go to is far from home.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "学院", pinyin: "xué yuàn", english: "college", sampleChinese: "这所学院有很多专业。", sampleEnglish: "This college offers many majors.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "要", pinyin: "yào", english: "want, need", sampleChinese: "我要一杯咖啡。", sampleEnglish: "I want a cup of coffee.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "爷爷", pinyin: "yé ye", english: "grandfather", sampleChinese: "我的爷爷喜欢讲故事。", sampleEnglish: "My grandfather enjoys telling stories.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "也", pinyin: "yě", english: "also", sampleChinese: "我也会游泳。", sampleEnglish: "I can swim too.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "页", pinyin: "yè", english: "page", sampleChinese: "请翻到第十页。", sampleEnglish: "Please turn to page ten.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一", pinyin: "yī", english: "one", sampleChinese: "我有一只猫。", sampleEnglish: "I have one cat.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "衣服", pinyin: "yī fú", english: "clothing", sampleChinese: "这是我的新衣服。", sampleEnglish: "This is my new clothing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "医生", pinyin: "yī shēng", english: "doctor", sampleChinese: "医生在医院工作。", sampleEnglish: "Doctors work in the hospital.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "医院", pinyin: "yī yuàn", english: "hospital", sampleChinese: "我去医院看望朋友。", sampleEnglish: "I'm going to the hospital to visit a friend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一半", pinyin: "yī bàn", english: "half", sampleChinese: "一半杯水。", sampleEnglish: "Half a cup of water.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一会儿", pinyin: "yī huìr", english: "a while", sampleChinese: "等一会儿。", sampleEnglish: "Wait a while.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一块儿", pinyin: "yī kuài er", english: "together", sampleChinese: "我们去吃饭一块儿。", sampleEnglish: "Let's go eat together.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一下儿", pinyin: "yī xiàr", english: "a moment", sampleChinese: "等一下儿，我马上回来。", sampleEnglish: "Wait a moment; I'll be right back.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一样", pinyin: "yī yàng", english: "the same", sampleChinese: "我们穿的衣服一样。", sampleEnglish: "We're wearing the same clothes.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一边", pinyin: "yī biān", english: "side", sampleChinese: "一边是大海，一边是山。", sampleEnglish: "One side is the sea, the other side is the mountain.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一点儿", pinyin: "yī diǎn er", english: "a little", sampleChinese: "加一点儿盐。", sampleEnglish: "Add a little salt.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一起", pinyin: "yī qǐ", english: "together", sampleChinese: "我们一起学习。", sampleEnglish: "We study together.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一些", pinyin: "yī xiē", english: "some", sampleChinese: "我想吃一些水果。", sampleEnglish: "I want to eat some fruit.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "用", pinyin: "yòng", english: "use", sampleChinese: "用这个刀切面包。", sampleEnglish: "Use this knife to cut the bread.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有", pinyin: "yǒu", english: "have, there is", sampleChinese: "我有一本书。", sampleEnglish: "I have a book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有的", pinyin: "yǒu de", english: "some", sampleChinese: "有的人喜欢雨天。", sampleEnglish: "Some people like rainy days.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有名", pinyin: "yǒu míng", english: "famous", sampleChinese: "这座山很有名。", sampleEnglish: "This mountain is very famous.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有时候", pinyin: "yǒu shí hou", english: "sometimes", sampleChinese: "有时候我喜欢安静。", sampleEnglish: "Sometimes I like it quiet.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有些", pinyin: "yǒu xiē", english: "some", sampleChinese: "这里有些好吃的。", sampleEnglish: "There is some delicious food here.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有用", pinyin: "yǒu yòng", english: "useful", sampleChinese: "这个工具很有用。", sampleEnglish: "This tool is very useful.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "右", pinyin: "yòu", english: "right", sampleChinese: "右拐是图书馆。", sampleEnglish: "Turn right for the library.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "右边", pinyin: "yòu biān", english: "right", sampleChinese: "我的包在右边。", sampleEnglish: "My bag is on the right.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "雨", pinyin: "yǔ", english: "rain", sampleChinese: "雨下得很大。", sampleEnglish: "The rain is heavy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "元", pinyin: "yuán", english: "yuan", sampleChinese: "这本书多少元？", sampleEnglish: "How much is this book?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "远", pinyin: "yuǎn", english: "far", sampleChinese: "我家离学校很远。", sampleEnglish: "My home is far from the school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "月", pinyin: "yuè", english: "month", sampleChinese: "这个月有三十一天。", sampleEnglish: "This month has 31 days.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "再", pinyin: "zài", english: "again", sampleChinese: "请再来一杯咖啡。", sampleEnglish: "Please bring another cup of coffee.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "再见", pinyin: "zài jiàn", english: "goodbye", sampleChinese: "明天再见！", sampleEnglish: "See you tomorrow!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "在", pinyin: "zài", english: "in, at", sampleChinese: "他在图书馆学习。", sampleEnglish: "He is studying in the library.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "在家", pinyin: "zài jiā", english: "at home", sampleChinese: "星期六我在家休息。", sampleEnglish: "I rest at home on Saturdays.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "早", pinyin: "zǎo", english: "early", sampleChinese: "早上好！", sampleEnglish: "Good morning!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "早饭", pinyin: "zǎo fàn", english: "breakfast", sampleChinese: "我每天吃早饭。", sampleEnglish: "I eat breakfast every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "早上", pinyin: "zǎo shang", english: "morning", sampleChinese: "我早上喜欢喝咖啡。", sampleEnglish: "I like to drink coffee in the morning.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "怎么", pinyin: "zěnme", english: "how", sampleChinese: "你怎么了？", sampleEnglish: "What's wrong with you?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "站", pinyin: "zhàn", english: "stand", sampleChinese: "请站在这里等一下。", sampleEnglish: "Please stand here and wait for a moment.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "找", pinyin: "zhǎo", english: "look for", sampleChinese: "我在找我的手机。", sampleEnglish: "I'm looking for my phone.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "找到", pinyin: "zhǎodào", english: "find", sampleChinese: "终于找到了丢失的钥匙。", sampleEnglish: "Finally found the lost keys.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "这", pinyin: "zhè", english: "this", sampleChinese: "这是我的书。", sampleEnglish: "This is my book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "这边", pinyin: "zhè biān", english: "here", sampleChinese: "请坐这边。", sampleEnglish: "Please sit here.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "这里", pinyin: "zhèlǐ", english: "here", sampleChinese: "我在这里等你。", sampleEnglish: "I'm waiting for you here.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "这儿", pinyin: "zhèr", english: "here", sampleChinese: "他住在这儿。", sampleEnglish: "He lives here.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "这些", pinyin: "zhèxiē", english: "these", sampleChinese: "这些是我的朋友。", sampleEnglish: "These are my friends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "着", pinyin: "zhe", english: "continuous aspect marker", sampleChinese: "她正在做饭。", sampleEnglish: "She is cooking.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "真", pinyin: "zhēn", english: "real", sampleChinese: "这个故事是真的吗？", sampleEnglish: "Is this story real?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "真的", pinyin: "zhēn de", english: "really", sampleChinese: "我真的很喜欢这个礼物。", sampleEnglish: "I really like this gift.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "正", pinyin: "zhèng", english: "right, just", sampleChinese: "她正忙着工作。", sampleEnglish: "She's busy working right now.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "正在", pinyin: "zhèngzài", english: "in the process of", sampleChinese: "他正在学习中文。", sampleEnglish: "He is learning Chinese.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "知道", pinyin: "zhīdào", english: "know", sampleChinese: "我知道答案。", sampleEnglish: "I know the answer.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "知识", pinyin: "zhīshì", english: "knowledge", sampleChinese: "学习知识是一种快乐。", sampleEnglish: "Learning knowledge is a joy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中", pinyin: "zhōng", english: "middle, center", sampleChinese: "他站在中间。", sampleEnglish: "He stands in the middle.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中国", pinyin: "zhōngguó", english: "China", sampleChinese: "中国是一个有悠久历史的国家。", sampleEnglish: "China is a country with a long history.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中间", pinyin: "zhōngjiān", english: "middle", sampleChinese: "桌子中间有一束鲜花。", sampleEnglish: "There's a bouquet of flowers in the middle of the table.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中文", pinyin: "zhōngwén", english: "Chinese language", sampleChinese: "学习中文很有趣。", sampleEnglish: "Learning Chinese is interesting.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中午", pinyin: "zhōngwǔ", english: "noon", sampleChinese: "我们中午吃午餐。", sampleEnglish: "We have lunch at noon.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中学", pinyin: "zhōngxué", english: "middle school", sampleChinese: "中学生学习各种学科。", sampleEnglish: "Middle school students study various subjects.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中学生", pinyin: "zhōngxuéshēng", english: "middle school student", sampleChinese: "这位中学生在图书馆学习。", sampleEnglish: "This middle school student is studying in the library.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "重", pinyin: "zhòng", english: "heavy", sampleChinese: "这箱子很重。", sampleEnglish: "This box is very heavy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "重要", pinyin: "zhòngyào", english: "important", sampleChinese: "健康对我们很重要。", sampleEnglish: "Health is important to us.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "住", pinyin: "zhù", english: "live", sampleChinese: "我住在城市中心。", sampleEnglish: "I live in the city center.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "准备", pinyin: "zhǔnbèi", english: "prepare", sampleChinese: "我要准备晚餐。", sampleEnglish: "I need to prepare dinner.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "桌子", pinyin: "zhuōzi", english: "table", sampleChinese: "这是我们用来吃饭的桌子。", sampleEnglish: "This is the table we use for eating.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "字", pinyin: "zì", english: "character", sampleChinese: "这个字很难写。", sampleEnglish: "This character is hard to write.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "子", pinyin: "zǐ", english: "child", sampleChinese: "她有两个子。", sampleEnglish: "She has two children.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "走", pinyin: "zǒu", english: "walk", sampleChinese: "我喜欢在公园散步。", sampleEnglish: "I like to walk in the park.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "走路", pinyin: "zǒulù", english: "walk", sampleChinese: "我通常走路上班。", sampleEnglish: "I usually walk to work.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "最", pinyin: "zuì", english: "most", sampleChinese: "这是我最喜欢的书。", sampleEnglish: "This is my most favorite book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "最好", pinyin: "zuì hǎo", english: "best", sampleChinese: "早睡早起身体最好。", sampleEnglish: "Early to bed and early to rise is best for your health.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "最后", pinyin: "zuìhòu", english: "last", sampleChinese: "最后一天是星期天。", sampleEnglish: "The last day is Sunday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "昨天", pinyin: "zuótiān", english: "yesterday", sampleChinese: "昨天我去了博物馆。", sampleEnglish: "I went to the museum yesterday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "左", pinyin: "zuǒ", english: "left", sampleChinese: "请左转。", sampleEnglish: "Please turn left.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "左边", pinyin: "zuǒbiān", english: "left", sampleChinese: "我的书包在左边。", sampleEnglish: "My backpack is on the left.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "坐", pinyin: "zuò", english: "sit", sampleChinese: "请坐下休息。", sampleEnglish: "Please sit down and rest.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "坐下", pinyin: "zuòxià", english: "sit down", sampleChinese: "坐下，别担心。", sampleEnglish: "Sit down, don't worry.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "做", pinyin: "zuò", english: "do", sampleChinese: "我要做我的作业。", sampleEnglish: "I need to do my homework.", rightInARow: 0, nextReviewDate: Date.now() }    
];

