const hsk1 = [
    { chinese: "这个", english: "this", sampleChinese: "这个东西很好，你喜欢吗？", sampleEnglish: "This thing is good, do you like it?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "爱", english: "love", sampleChinese: "他们之间有深厚的爱。", sampleEnglish: "There is deep love between them.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "爱好", english: "hobby", sampleChinese: "我的爱好是弹吉他。", sampleEnglish: "My hobby is playing the guitar.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "八", english: "eight", sampleChinese: "八点钟见！", sampleEnglish: "See you at eight o'clock!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "爸爸", english: "dad, father", sampleChinese: "我的爸爸每天早上都做早饭。", sampleEnglish: "My dad makes breakfast every morning.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "吧", english: "particle for suggestion", sampleChinese: "我们去吃饭吧，然后看电影。", sampleEnglish: "Let's go eat and then watch a movie.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "白", english: "white", sampleChinese: "她穿了一件白色的裙子。", sampleEnglish: "She is wearing a white dress.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "白天", english: "daytime", sampleChinese: "白天是学习的好时机。", sampleEnglish: "Daytime is a good time for studying.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "百", english: "hundred", sampleChinese: "这本书有一百页。", sampleEnglish: "This book has one hundred pages.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "班", english: "class", sampleChinese: "我在二班上课。", sampleEnglish: "I have classes in Class 2.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "半", english: "half", sampleChinese: "等我半小时，我就到了。", sampleEnglish: "Wait for me half an hour, and I'll be there.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "半年", english: "half a year", sampleChinese: "我去年度过了半年在国外。", sampleEnglish: "I spent half a year abroad last year.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "半天", english: "half a day", sampleChinese: "上午半天工作，下午休息。", sampleEnglish: "Work half a day in the morning, rest in the afternoon.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "帮", english: "to help", sampleChinese: "我可以帮你做作业。", sampleEnglish: "I can help you with your homework.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "帮忙", english: "to help", sampleChinese: "他经常帮忙照顾老人。", sampleEnglish: "He often helps take care of the elderly.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "包", english: "bag", sampleChinese: "我的包丢了，里面有我的钱包。", sampleEnglish: "I lost my bag, and my wallet was inside.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "包子", english: "steamed bun", sampleChinese: "我喜欢吃肉包子。", sampleEnglish: "I like eating meat buns.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "杯", english: "cup", sampleChinese: "请给我一杯咖啡。", sampleEnglish: "Please give me a cup of coffee.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "杯子", english: "cup, glass", sampleChinese: "这个玻璃杯子很漂亮。", sampleEnglish: "This glass is very beautiful.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "北", english: "north", sampleChinese: "北风吹得很凉爽。", sampleEnglish: "The north wind blows cool.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "北边", english: "north", sampleChinese: "北京在中国的北边。", sampleEnglish: "Beijing is in the north of China.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "北京", english: "Beijing", sampleChinese: "北京是中国的首都。", sampleEnglish: "Beijing is the capital of China.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "本", english: "this, root", sampleChinese: "这本书很有趣。", sampleEnglish: "This book is very interesting.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "本子", english: "notebook", sampleChinese: "我的笔记本子用完了。", sampleEnglish: "I've finished using my notebook.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "比", english: "compare", sampleChinese: "他比我更高。", sampleEnglish: "He is taller than me.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "别", english: "don't, other", sampleChinese: "别走，等等我！", sampleEnglish: "Don't go, wait for me!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "别的", english: "other", sampleChinese: "我还有别的事情要做。", sampleEnglish: "I have other things to do.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "别人", english: "other people", sampleChinese: "别人的问题不是你的责任。", sampleEnglish: "Other people's problems are not your responsibility.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "病", english: "illness", sampleChinese: "感冒是一种常见的疾病。", sampleEnglish: "The common cold is a common illness.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "病人", english: "patient", sampleChinese: "医院里有很多病人。", sampleEnglish: "There are many patients in the hospital.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "不大", english: "not big", sampleChinese: "这个房间不大，但很舒适。", sampleEnglish: "This room is not big, but it's very comfortable.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "不对", english: "not correct", sampleChinese: "你的答案不对。", sampleEnglish: "Your answer is not correct.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "不客气", english: "you're welcome", sampleChinese: "谢谢你的帮忙。不客气。", sampleEnglish: "Thank you for your help. You're welcome.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "不用", english: "not necessary", sampleChinese: "不用担心，一切都会好的。", sampleEnglish: "Don't worry, everything will be fine.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "不", english: "not", sampleChinese: "他不喜欢吃辣的食物。", sampleEnglish: "He doesn't like spicy food.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "菜", english: "vegetable, dish", sampleChinese: "我喜欢吃炒菜。", sampleEnglish: "I like to eat stir-fried vegetables.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "茶", english: "tea", sampleChinese: "你想要喝茶吗？", sampleEnglish: "Would you like to have some tea?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "差", english: "difference, to lack", sampleChinese: "这两个地方差不多。", sampleEnglish: "These two places are almost the same.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "常", english: "often", sampleChinese: "我常常去图书馆学习。", sampleEnglish: "I often go to the library to study.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "常常", english: "often", sampleChinese: "她常常在晚饭后锻炼。", sampleEnglish: "She often exercises after dinner.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "唱", english: "to sing", sampleChinese: "他喜欢唱流行歌曲。", sampleEnglish: "He likes to sing pop songs.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "唱歌", english: "to sing a song", sampleChinese: "我们一起唱歌吧！", sampleEnglish: "Let's sing a song together!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "车", english: "car", sampleChinese: "我没有自己的车。", sampleEnglish: "I don't have my own car.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "车票", english: "ticket", sampleChinese: "你买了火车票吗？", sampleEnglish: "Did you buy a train ticket?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "车上", english: "on the vehicle", sampleChinese: "在车上，请系好安全带。", sampleEnglish: "On the vehicle, please fasten your seatbelt.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "车站", english: "train station", sampleChinese: "我要去火车站接我的朋友。", sampleEnglish: "I'm going to the train station to pick up my friend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "吃", english: "to eat", sampleChinese: "我们一起去吃晚饭吧。", sampleEnglish: "Let's go eat dinner together.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "吃饭", english: "to have a meal", sampleChinese: "现在是吃饭的时间。", sampleEnglish: "Now is the time to have a meal.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "出", english: "to go out", sampleChinese: "我今天不想出门。", sampleEnglish: "I don't want to go out today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "出来", english: "to come out", sampleChinese: "请出来，我们需要谈一谈。", sampleEnglish: "Please come out; we need to talk.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "出去", english: "to go out", sampleChinese: "我们出去散步吧。", sampleEnglish: "Let's go out for a walk.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "穿", english: "to wear", sampleChinese: "今天天气冷，记得穿暖和一点。", sampleEnglish: "It's cold today, remember to wear something warm.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "床", english: "bed", sampleChinese: "我想躺在床上休息一下。", sampleEnglish: "I want to lie on the bed and rest for a while.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "次", english: "time, number of times", sampleChinese: "这是我第二次来中国。", sampleEnglish: "This is my second time in China.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "从", english: "from", sampleChinese: "我从学校回家。", sampleEnglish: "I'm going home from school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "错", english: "wrong", sampleChinese: "这个答案是错的。", sampleEnglish: "This answer is wrong.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "打", english: "to hit", sampleChinese: "他不应该打其他小孩。", sampleEnglish: "He shouldn't hit other kids.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "打车", english: "to take a taxi", sampleChinese: "我们需要打车去机场。", sampleEnglish: "We need to take a taxi to the airport.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "打电话", english: "to make a phone call", sampleChinese: "我给你打电话。", sampleEnglish: "I'll call you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "打开", english: "to open", sampleChinese: "请帮我打开窗户。", sampleEnglish: "Please help me open the window.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "打球", english: "to play ball", sampleChinese: "他们每周末打篮球。", sampleEnglish: "They play basketball every weekend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "大", english: "big", sampleChinese: "这个城市非常大。", sampleEnglish: "This city is very big.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "大学", english: "university", sampleChinese: "我在大学学习计算机科学。", sampleEnglish: "I study computer science at the university.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "大学生", english: "university student", sampleChinese: "他是一名大学生。", sampleEnglish: "He is a university student.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "到", english: "to arrive, to reach", sampleChinese: "我们准时到达了目的地。", sampleEnglish: "We arrived at our destination on time.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "得到", english: "to obtain", sampleChinese: "他终于得到了他梦寐以求的工作。", sampleEnglish: "He finally obtained the job he had been dreaming of.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地", english: "ground", sampleChinese: "这片地适合建房子吗？", sampleEnglish: "Is this ground suitable for building a house?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "的", english: "of", sampleChinese: "这是我的书的封面。", sampleEnglish: "This is the cover of my book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "等", english: "to wait", sampleChinese: "请等一下，我很快就回来。", sampleEnglish: "Please wait for a moment; I'll be back soon.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地", english: "ground", sampleChinese: "他摔倒在地上。", sampleEnglish: "He fell to the ground.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地点", english: "location", sampleChinese: "我们明天在同一个地点见面。", sampleEnglish: "Let's meet at the same location tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地方", english: "place", sampleChinese: "这是一个美丽的地方。", sampleEnglish: "This is a beautiful place.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地上", english: "on the ground", sampleChinese: "有一只猫躺在地上晒太阳。", sampleEnglish: "A cat is lying on the ground, basking in the sun.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "地图", english: "map", sampleChinese: "我迷路了，你能给我看看地图吗？", sampleEnglish: "I'm lost, can you show me the map?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "弟弟", english: "younger brother", sampleChinese: "我的弟弟很聪明。", sampleEnglish: "My younger brother is very smart.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "第", english: "number, order", sampleChinese: "这是第一次我来中国。", sampleEnglish: "This is the first time I've come to China.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "点", english: "point, o'clock", sampleChinese: "现在是八点。", sampleEnglish: "It's eight o'clock now.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电", english: "electricity", sampleChinese: "这个设备需要电吗？", sampleEnglish: "Does this device need electricity?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电话", english: "phone, telephone", sampleChinese: "我会给你打电话。", sampleEnglish: "I'll call you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电脑", english: "computer", sampleChinese: "我每天都使用电脑工作。", sampleEnglish: "I use a computer for work every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电视", english: "television", sampleChinese: "我喜欢看电视。", sampleEnglish: "I like watching TV.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电视机", english: "TV set", sampleChinese: "电视机放在客厅里。", sampleEnglish: "The TV set is in the living room.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电影", english: "movie", sampleChinese: "我们周末去看电影吧。", sampleEnglish: "Let's go watch a movie this weekend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "电影院", english: "cinema", sampleChinese: "这家电影院有最新的电影。", sampleEnglish: "This cinema has the latest movies.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "东", english: "east", sampleChinese: "太阳从东方升起。", sampleEnglish: "The sun rises in the east.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "东边", english: "east", sampleChinese: "图书馆在学校的东边。", sampleEnglish: "The library is on the east side of the school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "东西", english: "thing, stuff", sampleChinese: "我忘记了带东西。", sampleEnglish: "I forgot to bring my stuff.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "动", english: "to move", sampleChinese: "小狗在草地上动。", sampleEnglish: "The puppy is moving on the grass.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "动作", english: "action", sampleChinese: "他的动作很迅速。", sampleEnglish: "His actions are very fast.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "都", english: "all, both", sampleChinese: "他们都喜欢吃披萨。", sampleEnglish: "They both like pizza.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "读", english: "to read", sampleChinese: "我喜欢读小说。", sampleEnglish: "I like to read novels.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "读书", english: "to study, to read a book", sampleChinese: "晚上我常常在图书馆读书。", sampleEnglish: "I often study at the library in the evening.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "对", english: "correct, to face", sampleChinese: "这是正确的答案。", sampleEnglish: "This is the correct answer.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "对不起", english: "sorry", sampleChinese: "对不起，我迟到了。", sampleEnglish: "Sorry, I'm late.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "多", english: "many, much", sampleChinese: "这个城市有很多高楼。", sampleEnglish: "This city has many tall buildings.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "多少", english: "how much, how many", sampleChinese: "你们有多少钱？", sampleEnglish: "How much money do you have?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "饿", english: "hungry", sampleChinese: "我饿了，我要吃午饭。", sampleEnglish: "I'm hungry; I want to have lunch.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "儿子", english: "son", sampleChinese: "我儿子在学校学习。", sampleEnglish: "My son is studying at school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "二", english: "two", sampleChinese: "二加二等于四。", sampleEnglish: "Two plus two equals four.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "饭", english: "meal, cooked rice", sampleChinese: "晚饭的时候我喜欢吃米饭。", sampleEnglish: "I like to eat rice for dinner.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "饭店", english: "restaurant", sampleChinese: "我们去附近的饭店吃晚饭。", sampleEnglish: "Let's go to a nearby restaurant for dinner.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "房间", english: "room", sampleChinese: "这个酒店的房间很宽敞。", sampleEnglish: "The rooms in this hotel are spacious.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "房子", english: "house", sampleChinese: "我梦想有一所漂亮的房子。", sampleEnglish: "I dream of having a beautiful house.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "放", english: "to put, to place", sampleChinese: "把书放在桌子上。", sampleEnglish: "Put the book on the table.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "放假", english: "to have a holiday", sampleChinese: "每年夏天，我都会放假去旅行。", sampleEnglish: "Every summer, I take a holiday to travel.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "放学", english: "school's out", sampleChinese: "孩子们放学后通常会去公园玩。", sampleEnglish: "Children usually go to the park to play after school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "飞", english: "to fly", sampleChinese: "飞机从机场起飞。", sampleEnglish: "The plane takes off from the airport.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "飞机", english: "airplane", sampleChinese: "我坐飞机去了上海。", sampleEnglish: "I took a plane to Shanghai.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "非常", english: "very", sampleChinese: "今天天气非常热。", sampleEnglish: "The weather is very hot today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "分", english: "minute, to divide", sampleChinese: "这个任务需要十分钟。", sampleEnglish: "This task will take ten minutes.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "风", english: "wind", sampleChinese: "海边的风非常凉爽。", sampleEnglish: "The wind by the sea is very refreshing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "干", english: "to do", sampleChinese: "他每天都干很多工作。", sampleEnglish: "He does a lot of work every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "干净", english: "clean", sampleChinese: "这个房间很干净。", sampleEnglish: "This room is very clean.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "干", english: "dry", sampleChinese: "请把湿衣服晾干。", sampleEnglish: "Please hang wet clothes to dry.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "干什么", english: "to do what", sampleChinese: "你今天晚上要干什么？", sampleEnglish: "What are you going to do tonight?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "高", english: "tall, high", sampleChinese: "这座山非常高。", sampleEnglish: "This mountain is very high.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "高兴", english: "happy", sampleChinese: "他听到这个好消息后非常高兴。", sampleEnglish: "He was very happy when he heard the good news.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "告诉", english: "to tell", sampleChinese: "请告诉我你的名字。", sampleEnglish: "Please tell me your name.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "哥哥", english: "older brother", sampleChinese: "我哥哥比我大两岁。", sampleEnglish: "My older brother is two years older than me.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "歌", english: "song", sampleChinese: "这是一首美丽的歌曲。", sampleEnglish: "This is a beautiful song.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "个", english: "measure word for individuals", sampleChinese: "我有一个好朋友。", sampleEnglish: "I have a good friend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "给", english: "to give", sampleChinese: "我给你一本书。", sampleEnglish: "I'll give you a book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "跟", english: "with", sampleChinese: "我今天跟朋友一起去购物。", sampleEnglish: "I'm going shopping with friends today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "工人", english: "worker", sampleChinese: "这个工人每天都在建造房子。", sampleEnglish: "The worker is building houses every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "工作", english: "work, to work", sampleChinese: "我明天要早点去工作。", sampleEnglish: "I need to go to work early tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "关", english: "to close", sampleChinese: "请把门关上。", sampleEnglish: "Please close the door.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "关上", english: "to close (something)", sampleChinese: "关上窗户，不然会下雨进来。", sampleEnglish: "Close the window, or rain will come in.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "贵", english: "expensive", sampleChinese: "这个手表很贵。", sampleEnglish: "This watch is very expensive.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "国", english: "country", sampleChinese: "中国是一个大国。", sampleEnglish: "China is a big country.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "国家", english: "country", sampleChinese: "每个国家都有自己的文化。", sampleEnglish: "Every country has its own culture.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "国外", english: "overseas", sampleChinese: "我梦想去国外旅行。", sampleEnglish: "I dream of traveling overseas.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "过", english: "to pass, to spend", sampleChinese: "时间过得真快。", sampleEnglish: "Time passes quickly.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "还", english: "still, yet", sampleChinese: "我还没吃早饭。", sampleEnglish: "I haven't eaten breakfast yet.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "还是", english: "or", sampleChinese: "你喜欢咖啡还是茶？", sampleEnglish: "Do you like coffee or tea?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "还有", english: "also, furthermore", sampleChinese: "我要买苹果还有橙子。", sampleEnglish: "I want to buy apples and oranges.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "孩子", english: "child", sampleChinese: "这是我的孩子，她很聪明。", sampleEnglish: "This is my child; she is very smart.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "汉语", english: "Chinese language", sampleChinese: "学习汉语需要耐心。", sampleEnglish: "Learning Chinese language requires patience.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "汉字", english: "Chinese characters", sampleChinese: "汉字是中国文字的一部分。", sampleEnglish: "Chinese characters are part of Chinese writing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "好", english: "good", sampleChinese: "这是一个好消息。", sampleEnglish: "This is good news.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "好吃", english: "delicious", sampleChinese: "这个菜真好吃。", sampleEnglish: "This dish is really delicious.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "好看", english: "good-looking", sampleChinese: "她穿这件衣服很好看。", sampleEnglish: "She looks good in this outfit.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "好听", english: "pleasant to hear", sampleChinese: "这首歌非常好听。", sampleEnglish: "This song is very pleasant to hear.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "好玩儿", english: "fun", sampleChinese: "这个游乐园很好玩儿。", sampleEnglish: "This amusement park is a lot of fun.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "号", english: "number", sampleChinese: "今天是几号？", sampleEnglish: "What is the date today?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "喝", english: "to drink", sampleChinese: "你想喝点什么？", sampleEnglish: "What would you like to drink?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "和", english: "and", sampleChinese: "我喜欢咖啡和茶。", sampleEnglish: "I like coffee and tea.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "很", english: "very", sampleChinese: "他是一个很好的朋友。", sampleEnglish: "He is a very good friend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "后", english: "after", sampleChinese: "晚饭后，我喜欢散步。", sampleEnglish: "After dinner, I like to take a walk.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "后边", english: "behind", sampleChinese: "请站在我后边。", sampleEnglish: "Please stand behind me.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "后天", english: "the day after tomorrow", sampleChinese: "我们后天去旅行。", sampleEnglish: "We're going on a trip the day after tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "花", english: "flower", sampleChinese: "这朵花美丽。", sampleEnglish: "This flower is beautiful.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "话", english: "talk", sampleChinese: "我们聊聊吧。", sampleEnglish: "Let's talk.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "坏", english: "bad", sampleChinese: "这个电池坏了。", sampleEnglish: "This battery is bad.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "还", english: "still", sampleChinese: "我还在等你。", sampleEnglish: "I'm still waiting for you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回", english: "return", sampleChinese: "我马上回来。", sampleEnglish: "I'll be right back.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回答", english: "answer", sampleChinese: "请回答这个问题。", sampleEnglish: "Please answer this question.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回到", english: "return to", sampleChinese: "他回到故乡。", sampleEnglish: "He returned to his hometown.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回家", english: "go home", sampleChinese: "我渴望回家。", sampleEnglish: "I long to go home.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回来", english: "come back", sampleChinese: "他答应很快回来。", sampleEnglish: "He promised to come back soon.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "回去", english: "go back", sampleChinese: "现在是时候回去了。", sampleEnglish: "It's time to go back now.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "会", english: "will", sampleChinese: "明天会晴朗。", sampleEnglish: "Tomorrow will be sunny.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "火车", english: "train", sampleChinese: "我喜欢坐火车。", sampleEnglish: "I like taking the train.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "机场", english: "airport", sampleChinese: "机场繁忙。", sampleEnglish: "The airport is busy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "机票", english: "plane ticket", sampleChinese: "我已预订机票。", sampleEnglish: "I've booked the plane ticket.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "鸡蛋", english: "egg", sampleChinese: "我要煮鸡蛋。", sampleEnglish: "I want to cook eggs.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "几", english: "how many", sampleChinese: "你几点来？", sampleEnglish: "What time will you come?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "记", english: "to record", sampleChinese: "请记下这个电话号码。", sampleEnglish: "Please record this phone number.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "记得", english: "to remember", sampleChinese: "我记得你的名字。", sampleEnglish: "I remember your name.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "记住", english: "to memorize", sampleChinese: "你要记住这些单词。", sampleEnglish: "You should memorize these words.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "家", english: "home", sampleChinese: "我在家里。", sampleEnglish: "I am at home.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "家里", english: "at home", sampleChinese: "爸爸在家里。", sampleEnglish: "Dad is at home.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "家人", english: "family member", sampleChinese: "我的家人很亲切。", sampleEnglish: "My family members are very kind.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "间", english: "room", sampleChinese: "这是我的卧室。", sampleEnglish: "This is my bedroom.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "见", english: "to see", sampleChinese: "我想见你。", sampleEnglish: "I want to see you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "见面", english: "to meet", sampleChinese: "我们明天见面。", sampleEnglish: "We'll meet tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "教", english: "to teach", sampleChinese: "老师教我们汉字。", sampleEnglish: "The teacher teaches us Chinese characters.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "叫", english: "to call", sampleChinese: "请叫我一声老师。", sampleEnglish: "Please call me 'teacher'.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "教学楼", english: "teaching building", sampleChinese: "教学楼在前面。", sampleEnglish: "The teaching building is in front.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "姐姐", english: "older sister", sampleChinese: "我有一个姐姐。", sampleEnglish: "I have an older sister.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "介绍", english: "to introduce", sampleChinese: "请介绍一下你自己。", sampleEnglish: "Please introduce yourself.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "今年", english: "this year", sampleChinese: "今年是兔年。", sampleEnglish: "This year is the Year of the Rabbit.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "今天", english: "today", sampleChinese: "今天天气很好。", sampleEnglish: "The weather is nice today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "进", english: "to enter", sampleChinese: "请进来。", sampleEnglish: "Please come in.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "进来", english: "to come in", sampleChinese: "你可以进来吗？", sampleEnglish: "Can you come in?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "进去", english: "to go in", sampleChinese: "他要进去一下。", sampleEnglish: "He's going in for a moment.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "九", english: "nine", sampleChinese: "九是一个幸运数字。", sampleEnglish: "Nine is a lucky number.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "就", english: "just", sampleChinese: "我就来了。", sampleEnglish: "I just arrived.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "觉得", english: "to feel", sampleChinese: "我觉得很高兴。", sampleEnglish: "I feel very happy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "开", english: "to open", sampleChinese: "请开门。", sampleEnglish: "Please open the door.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "开车", english: "to drive", sampleChinese: "他会开车。", sampleEnglish: "He can drive.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "开会", english: "to have a meeting", sampleChinese: "他们明天要开会。", sampleEnglish: "They are going to have a meeting tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "开玩笑", english: "to joke", sampleChinese: "他在开玩笑吗？", sampleEnglish: "Is he joking?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "看", english: "to look at", sampleChinese: "我想看这本书。", sampleEnglish: "I want to look at this book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "看病", english: "to see a doctor", sampleChinese: "他生病了，需要看病。", sampleEnglish: "He is sick and needs to see a doctor.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "看到", english: "to see", sampleChinese: "我看到了你的消息。", sampleEnglish: "I saw your message.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "看见", english: "to see", sampleChinese: "我看见了一只小狗。", sampleEnglish: "I saw a little dog.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "考", english: "to take an exam", sampleChinese: "明天我要考数学考试。", sampleEnglish: "I have a math exam tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "考试", english: "exam", sampleChinese: "期末考试很重要。", sampleEnglish: "Final exams are important.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "渴", english: "thirsty", sampleChinese: "我很渴，想喝水。", sampleEnglish: "I'm very thirsty and want to drink water.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "课", english: "class", sampleChinese: "我今天有汉语课。", sampleEnglish: "I have Chinese class today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "课本", english: "textbook", sampleChinese: "我的课本在书包里。", sampleEnglish: "My textbook is in my backpack.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "课文", english: "text of a lesson", sampleChinese: "我们要读这篇课文。", sampleEnglish: "We have to read this lesson's text.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "口", english: "mouth", sampleChinese: "用你的口说话。", sampleEnglish: "Speak with your mouth.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "块", english: "piece", sampleChinese: "这块蛋糕很好吃。", sampleEnglish: "This piece of cake is delicious.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "快", english: "fast", sampleChinese: "他跑得很快。", sampleEnglish: "He runs very fast.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "来", english: "to come", sampleChinese: "我明天来。", sampleEnglish: "I'll come tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "来到", english: "to arrive", sampleChinese: "他已经来到了机场。", sampleEnglish: "He has already arrived at the airport.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "老", english: "old", sampleChinese: "这辆车很老了。", sampleEnglish: "This car is very old.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "老人", english: "old person", sampleChinese: "老人们喜欢在公园散步。", sampleEnglish: "Old people like to take walks in the park.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "老师", english: "teacher", sampleChinese: "我的老师很聪明。", sampleEnglish: "My teacher is very smart.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "了", english: "particle for past tense", sampleChinese: "我吃了晚饭。", sampleEnglish: "I ate dinner.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "累", english: "tired", sampleChinese: "他工作一整天，现在很累。", sampleEnglish: "He worked all day and is very tired.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "冷", english: "cold", sampleChinese: "今天天气很冷。", sampleEnglish: "The weather is very cold today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "里", english: "inside", sampleChinese: "手机在包里。", sampleEnglish: "The phone is inside the bag.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "里边", english: "inside", sampleChinese: "请把东西放在盒子里边。", sampleEnglish: "Please put the things inside the box.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "两", english: "two", sampleChinese: "我有两个弟弟。", sampleEnglish: "I have two younger brothers.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "零", english: "zero", sampleChinese: "这个数字是零。", sampleEnglish: "This number is zero.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "六", english: "six", sampleChinese: "六只猫在院子里。", sampleEnglish: "There are six cats in the yard.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "楼", english: "floor", sampleChinese: "我住在第五楼。", sampleEnglish: "I live on the fifth floor.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "楼上", english: "upstairs", sampleChinese: "厕所在楼上。", sampleEnglish: "The restroom is upstairs.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "楼下", english: "downstairs", sampleChinese: "他在楼下等你。", sampleEnglish: "He's waiting for you downstairs.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "路", english: "road", sampleChinese: "这条路很宽。", sampleEnglish: "This road is very wide.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "路口", english: "intersection", sampleChinese: "在路口左转。", sampleEnglish: "Turn left at the intersection.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "路上", english: "on the road", sampleChinese: "路上有很多车。", sampleEnglish: "There are a lot of cars on the road.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "妈妈", english: "mom", sampleChinese: "我的妈妈很疼爱我。", sampleEnglish: "My mom loves me very much.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "马路", english: "road, street", sampleChinese: "过马路要小心。", sampleEnglish: "Be careful when crossing the street.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "马上", english: "immediately", sampleChinese: "我马上回来。", sampleEnglish: "I'll be back immediately.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "吗", english: "question particle", sampleChinese: "你好吗？", sampleEnglish: "How are you?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "买", english: "to buy", sampleChinese: "我要去买东西。", sampleEnglish: "I'm going to buy some things.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "慢", english: "slow", sampleChinese: "他跑得很慢。", sampleEnglish: "He runs very slowly.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "忙", english: "busy", sampleChinese: "我很忙，没时间。", sampleEnglish: "I'm busy and don't have time.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "毛", english: "fur, hair", sampleChinese: "这只猫的毛很软。", sampleEnglish: "This cat's fur is very soft.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "没", english: "not", sampleChinese: "我没吃饭。", sampleEnglish: "I haven't eaten.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "没关系", english: "it's okay", sampleChinese: "没关系，我们可以再试一次。", sampleEnglish: "It's okay, we can try again.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "没什么", english: "it's nothing", sampleChinese: "没什么，别担心。", sampleEnglish: "It's nothing, don't worry.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "没事儿", english: "it's okay", sampleChinese: "我没事儿，谢谢。", sampleEnglish: "I'm okay, thanks.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "没有", english: "not have", sampleChinese: "他没有手机。", sampleEnglish: "He doesn't have a phone.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "妹妹", english: "sister", sampleChinese: "我的妹妹很可爱。", sampleEnglish: "My sister is very cute.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "门", english: "door", sampleChinese: "请关上门。", sampleEnglish: "Please close the door.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "门口", english: "doorway", sampleChinese: "他站在门口等你。", sampleEnglish: "He's standing in the doorway waiting for you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "门票", english: "entrance ticket", sampleChinese: "门票多少钱？", sampleEnglish: "How much is the entrance ticket?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "们", english: "plural marker", sampleChinese: "我们是好朋友。", sampleEnglish: "We are good friends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "米饭", english: "rice", sampleChinese: "我喜欢吃米饭。", sampleEnglish: "I like to eat rice.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "面包", english: "bread", sampleChinese: "早餐吃面包很常见。", sampleEnglish: "Eating bread for breakfast is common.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "面条儿", english: "noodles", sampleChinese: "面条儿很好吃。", sampleEnglish: "Noodles are very delicious.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "名字", english: "name", sampleChinese: "你叫什么名字？", sampleEnglish: "What's your name?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "明白", english: "to understand", sampleChinese: "我明白了你的意思。", sampleEnglish: "I understand what you mean.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "明年", english: "next year", sampleChinese: "明年我要去旅行。", sampleEnglish: "I'm going to travel next year.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "明天", english: "tomorrow", sampleChinese: "明天是周末。", sampleEnglish: "Tomorrow is the weekend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "拿", english: "to take, to hold", sampleChinese: "请拿给我。", sampleEnglish: "Please hand it to me.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "哪", english: "where", sampleChinese: "哪个是你的书？", sampleEnglish: "Which one is your book?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "哪里", english: "where", sampleChinese: "你住在哪里？", sampleEnglish: "Where do you live?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "哪儿", english: "where", sampleChinese: "你去哪儿？", sampleEnglish: "Where are you going?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "哪些", english: "which", sampleChinese: "你喜欢哪些水果？", sampleEnglish: "Which fruits do you like?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "那", english: "that", sampleChinese: "那是我的书。", sampleEnglish: "That is my book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "那边", english: "there", sampleChinese: "她在那边等你。", sampleEnglish: "She's waiting for you over there.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "那里", english: "there", sampleChinese: "那里有一家好饭馆。", sampleEnglish: "There's a good restaurant over there.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "那儿", english: "there", sampleChinese: "我们去那儿玩。", sampleEnglish: "Let's go play there.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "那些", english: "those", sampleChinese: "那些书是我的。", sampleEnglish: "Those books are mine.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "奶", english: "milk", sampleChinese: "我要一杯奶。", sampleEnglish: "I'd like a glass of milk.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "奶奶", english: "grandmother", sampleChinese: "我的奶奶很慈祥。", sampleEnglish: "My grandmother is very kind.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "男", english: "male", sampleChinese: "男人和女人。", sampleEnglish: "Men and women.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "男孩儿", english: "boy", sampleChinese: "这是一个聪明的男孩儿。", sampleEnglish: "This is a clever boy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "男朋友", english: "boyfriend", sampleChinese: "她的男朋友很帅。", sampleEnglish: "Her boyfriend is handsome.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "男人", english: "man", sampleChinese: "这位男人是医生。", sampleEnglish: "This man is a doctor.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "男生", english: "male student", sampleChinese: "男生和女生都来参加。", sampleEnglish: "Both male and female students are coming to participate.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "南", english: "south", sampleChinese: "南边有一座山。", sampleEnglish: "There's a mountain to the south.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "南边", english: "south", sampleChinese: "我的家在南边。", sampleEnglish: "My home is in the south.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "难", english: "difficult", sampleChinese: "这个问题很难。", sampleEnglish: "This question is difficult.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "呢", english: "question particle", sampleChinese: "你呢？", sampleEnglish: "What about you?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "能", english: "can", sampleChinese: "我能帮助你。", sampleEnglish: "I can help you.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "你", english: "you", sampleChinese: "你好吗？", sampleEnglish: "How are you?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "你们", english: "you all", sampleChinese: "你们都是我的朋友。", sampleEnglish: "You all are my friends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "年", english: "year", sampleChinese: "明年是新的一年。", sampleEnglish: "Next year is a new year.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "您", english: "you (polite)", sampleChinese: "您的座位在哪里？", sampleEnglish: "Where is your seat?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "牛奶", english: "milk", sampleChinese: "牛奶是健康的。", sampleEnglish: "Milk is healthy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女", english: "female", sampleChinese: "男女平等。", sampleEnglish: "Gender equality.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女儿", english: "daughter", sampleChinese: "她是我的女儿。", sampleEnglish: "She is my daughter.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女孩儿", english: "girl", sampleChinese: "那是一个聪明的女孩儿。", sampleEnglish: "That's a clever girl.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女朋友", english: "girlfriend", sampleChinese: "她的女朋友很漂亮。", sampleEnglish: "Her girlfriend is pretty.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女人", english: "woman", sampleChinese: "女人和男人。", sampleEnglish: "Women and men.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "女生", english: "female student", sampleChinese: "女生都非常用功。", sampleEnglish: "Female students are all very hardworking.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "旁边", english: "beside", sampleChinese: "书在桌子旁边。", sampleEnglish: "The book is beside the table.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "跑", english: "to run", sampleChinese: "他喜欢跑步。", sampleEnglish: "He likes to run.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "朋友", english: "friend", sampleChinese: "朋友们一起玩。", sampleEnglish: "Friends play together.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "票", english: "ticket", sampleChinese: "我要买电影票。", sampleEnglish: "I want to buy movie tickets.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "七", english: "seven", sampleChinese: "七天一周。", sampleEnglish: "Seven days in a week.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "起", english: "to rise", sampleChinese: "太阳已经起来了。", sampleEnglish: "The sun has risen.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "起床", english: "to get up", sampleChinese: "早上你什么时候起床？", sampleEnglish: "What time do you get up in the morning?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "起来", english: "to stand up", sampleChinese: "请大家都站起来。", sampleEnglish: "Please everyone stand up.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "汽车", english: "car", sampleChinese: "这是我的汽车。", sampleEnglish: "This is my car.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "前", english: "front", sampleChinese: "请坐在前面。", sampleEnglish: "Please sit in the front.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "前边", english: "in front", sampleChinese: "餐厅在房间的前边。", sampleEnglish: "The dining room is in front of the room.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "前天", english: "the day before yesterday", sampleChinese: "前天我去了图书馆。", sampleEnglish: "I went to the library the day before yesterday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "钱", english: "money", sampleChinese: "这是我的钱包。", sampleEnglish: "This is my wallet.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "钱包", english: "wallet", sampleChinese: "我丢了我的钱包。", sampleEnglish: "I lost my wallet.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "请", english: "please", sampleChinese: "请坐下。", sampleEnglish: "Please have a seat.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "请假", english: "to ask for leave", sampleChinese: "他因病请假。", sampleEnglish: "He asked for leave due to illness.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "请进", english: "please come in", sampleChinese: "请进，别客气。", sampleEnglish: "Please come in, don't be shy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "请问", english: "please ask", sampleChinese: "请问这里有餐厅吗？", sampleEnglish: "May I ask if there is a restaurant here?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "请坐", english: "please sit", sampleChinese: "请坐下，别拘谨。", sampleEnglish: "Please sit down, don't be formal.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "球", english: "ball", sampleChinese: "我们去打篮球吧。", sampleEnglish: "Let's go play basketball.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "去", english: "go", sampleChinese: "我要去商店。", sampleEnglish: "I want to go to the store.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "去年", english: "last year", sampleChinese: "去年的生日派对很开心。", sampleEnglish: "Last year's birthday party was fun.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "热", english: "hot", sampleChinese: "今天很热。", sampleEnglish: "It's very hot today.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "人", english: "person", sampleChinese: "这是我的朋友，他是个好人。", sampleEnglish: "This is my friend; he's a good person.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "认识", english: "to know", sampleChinese: "你认识这位老师吗？", sampleEnglish: "Do you know this teacher?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "认真", english: "serious", sampleChinese: "他对工作非常认真。", sampleEnglish: "He is very serious about his work.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "日", english: "day", sampleChinese: "今天是星期一，明天是星期二。", sampleEnglish: "Today is Monday, and tomorrow is Tuesday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "日期", english: "date", sampleChinese: "请告诉我今天的日期。", sampleEnglish: "Please tell me today's date.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "肉", english: "meat", sampleChinese: "我喜欢吃牛肉。", sampleEnglish: "I like to eat beef.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "三", english: "three", sampleChinese: "三只小猫在玩耍。", sampleEnglish: "Three kittens are playing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "山", english: "mountain", sampleChinese: "那座山非常高。", sampleEnglish: "That mountain is very high.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "商场", english: "shopping mall", sampleChinese: "周末我们去商场购物。", sampleEnglish: "We go shopping at the mall on weekends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "商店", english: "store", sampleChinese: "这家商店有很多衣服。", sampleEnglish: "This store has a lot of clothes.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上", english: "above", sampleChinese: "请把杯子放在桌子上。", sampleEnglish: "Please put the cup on the table.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上班", english: "go to work", sampleChinese: "他每天早上七点上班。", sampleEnglish: "He goes to work at 7 AM every morning.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上边", english: "above", sampleChinese: "飞机在云层上边飞行。", sampleEnglish: "The plane is flying above the clouds.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上车", english: "get on the car", sampleChinese: "快上车，我们要出发了。", sampleEnglish: "Hurry up and get on the car; we're about to leave.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上次", english: "last time", sampleChinese: "上次去海滩是在去年。", sampleEnglish: "The last time I went to the beach was last year.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上课", english: "attend a class", sampleChinese: "我们明天上课。", sampleEnglish: "We have class tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上网", english: "go online", sampleChinese: "晚上我喜欢上网冲浪。", sampleEnglish: "I like to go online surfing at night.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上午", english: "morning", sampleChinese: "上午十点是开会时间。", sampleEnglish: "The meeting is at 10 AM in the morning.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "上学", english: "go to school", sampleChinese: "孩子们都喜欢上学。", sampleEnglish: "Children all like to go to school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "少", english: "few", sampleChinese: "这个城市的人口很少。", sampleEnglish: "The population of this city is very small.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "谁", english: "who", sampleChinese: "谁来过这里？", sampleEnglish: "Who has been here?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "身上", english: "on one's body", sampleChinese: "我的钥匙在我的包里或者身上。", sampleEnglish: "My keys are in my bag or on my body.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "身体", english: "body", sampleChinese: "保持身体健康很重要。", sampleEnglish: "It's important to keep your body healthy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "什么", english: "what", sampleChinese: "你在想什么？", sampleEnglish: "What are you thinking about?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "生病", english: "get sick", sampleChinese: "他生病了，不能去上学。", sampleEnglish: "He's sick and can't go to school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "生气", english: "get angry", sampleChinese: "不要生气，事情会好起来的。", sampleEnglish: "Don't get angry; things will get better.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "生日", english: "birthday", sampleChinese: "今天是我的生日。", sampleEnglish: "Today is my birthday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "十", english: "ten", sampleChinese: "这是十块钱。", sampleEnglish: "This is ten dollars.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "时候", english: "time", sampleChinese: "晚上是一个看电影的好时候。", sampleEnglish: "Evening is a good time to watch a movie.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "时间", english: "time", sampleChinese: "我没有足够的时间去购物。", sampleEnglish: "I don't have enough time to go shopping.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "事", english: "thing", sampleChinese: "这是一件好事。", sampleEnglish: "This is a good thing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "试", english: "try", sampleChinese: "不要害怕尝试新东西。", sampleEnglish: "Don't be afraid to try new things.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "是", english: "is", sampleChinese: "这是我的手机。", sampleEnglish: "This is my phone.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "是不是", english: "whether or not", sampleChinese: "你确定是不是这个答案？", sampleEnglish: "Are you sure whether this is the answer or not?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "手", english: "hand", sampleChinese: "请把东西放在我手里。", sampleEnglish: "Please put the thing in my hand.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "手机", english: "mobile phone", sampleChinese: "我把手机落在家里了。", sampleEnglish: "I left my mobile phone at home.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "书", english: "book", sampleChinese: "我喜欢读书。", sampleEnglish: "I like reading books.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "书包", english: "school bag", sampleChinese: "我需要一个新书包。", sampleEnglish: "I need a new school bag.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "书店", english: "bookstore", sampleChinese: "我经常去书店购买书。", sampleEnglish: "I often go to the bookstore to buy books.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "树", english: "tree", sampleChinese: "公园里有很多漂亮的树。", sampleEnglish: "There are many beautiful trees in the park.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "水", english: "water", sampleChinese: "水是生命之源。", sampleEnglish: "Water is the source of life.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "水果", english: "fruit", sampleChinese: "我早餐吃了一些水果。", sampleEnglish: "I had some fruit for breakfast.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "睡", english: "sleep", sampleChinese: "晚上好，我去睡觉了。", sampleEnglish: "Good night, I'm going to sleep.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "睡觉", english: "go to sleep", sampleChinese: "晚上好，该睡觉了。", sampleEnglish: "Good evening, it's time to go to sleep.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "说", english: "say", sampleChinese: "你想对我说什么？", sampleEnglish: "What do you want to say to me?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "说话", english: "speak", sampleChinese: "请不要在课堂上说话。", sampleEnglish: "Please don't speak in the classroom.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "四", english: "four", sampleChinese: "有四个季节。", sampleEnglish: "There are four seasons.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "送", english: "give", sampleChinese: "他送了一份礼物给她。", sampleEnglish: "He gave her a gift.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "岁", english: "years old", sampleChinese: "她五岁了。", sampleEnglish: "She is five years old.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "他", english: "he", sampleChinese: "他是我的朋友。", sampleEnglish: "He is my friend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "他们", english: "they", sampleChinese: "他们正在学习中文。", sampleEnglish: "They are learning Chinese.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "她", english: "she", sampleChinese: "她非常聪明。", sampleEnglish: "She is very smart.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "她们", english: "they (feminine)", sampleChinese: "她们是好朋友。", sampleEnglish: "They are good friends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "太", english: "too", sampleChinese: "这个苹果太甜了。", sampleEnglish: "This apple is too sweet.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "天", english: "day", sampleChinese: "今天是晴天。", sampleEnglish: "Today is a sunny day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "天气", english: "weather", sampleChinese: "天气预报说明天会下雨。", sampleEnglish: "The weather forecast says it will rain tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "听", english: "listen", sampleChinese: "请安静地听老师讲课。", sampleEnglish: "Please listen quietly to the teacher's lecture.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "听到", english: "hear", sampleChinese: "我听到了她的歌声。", sampleEnglish: "I heard her singing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "听见", english: "hear", sampleChinese: "我听见了一声巨响。", sampleEnglish: "I heard a loud noise.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "听写", english: "dictation", sampleChinese: "明天我们要做听写练习。", sampleEnglish: "We will do a dictation exercise tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "同学", english: "classmate", sampleChinese: "我的同学都很友好。", sampleEnglish: "My classmates are all very friendly.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "图书馆", english: "library", sampleChinese: "图书馆是学习的好地方。", sampleEnglish: "The library is a good place to study.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "外", english: "outside", sampleChinese: "外面下雨了。", sampleEnglish: "It's raining outside.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "外边", english: "outside", sampleChinese: "请在外边等一下。", sampleEnglish: "Please wait outside for a moment.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "外国", english: "foreign country", sampleChinese: "我想去外国旅行。", sampleEnglish: "I want to travel to a foreign country.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "外语", english: "foreign language", sampleChinese: "学习外语需要耐心。", sampleEnglish: "Learning a foreign language requires patience.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "玩儿", english: "play", sampleChinese: "孩子们在公园里玩得很开心。", sampleEnglish: "The kids are playing happily in the park.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "晚", english: "late", sampleChinese: "我会回家很晚。", sampleEnglish: "I will go home late.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "晚饭", english: "dinner", sampleChinese: "晚饭后我们去看电影。", sampleEnglish: "We'll go to the movies after dinner.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "晚上", english: "evening", sampleChinese: "我喜欢在晚上散步。", sampleEnglish: "I like to take a walk in the evening.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "网上", english: "online", sampleChinese: "你可以在网上购物。", sampleEnglish: "You can shop online.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "网友", english: "online friend", sampleChinese: "我认识了很多网友。", sampleEnglish: "I've made many online friends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "忘", english: "forget", sampleChinese: "不要忘了明天的约会。", sampleEnglish: "Don't forget our meeting tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "忘记", english: "forget", sampleChinese: "我忘记了那个密码。", sampleEnglish: "I forgot that password.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "问", english: "ask", sampleChinese: "如果有问题，就问老师。", sampleEnglish: "If you have questions, ask the teacher.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "我", english: "I, me", sampleChinese: "我喜欢学习新东西。", sampleEnglish: "I enjoy learning new things.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "我们", english: "we, us", sampleChinese: "我们一起庆祝生日。", sampleEnglish: "We celebrate birthdays together.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "五", english: "five", sampleChinese: "五个苹果。", sampleEnglish: "Five apples.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "午饭", english: "lunch", sampleChinese: "午饭时间到了。", sampleEnglish: "It's lunchtime.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "西", english: "west", sampleChinese: "太阳在西边落山。", sampleEnglish: "The sun sets in the west.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "西边", english: "west", sampleChinese: "我家在城市的西边。", sampleEnglish: "My house is on the west side of the city.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "洗", english: "wash", sampleChinese: "我要洗衣服了。", sampleEnglish: "I need to wash the clothes.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "洗手间", english: "bathroom", sampleChinese: "洗手间在房间的尽头。", sampleEnglish: "The bathroom is at the end of the hallway.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "喜欢", english: "like", sampleChinese: "我喜欢吃冰淇淋。", sampleEnglish: "I like to eat ice cream.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下", english: "below", sampleChinese: "请看下面的表格。", sampleEnglish: "Please check the table below.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下班", english: "get off work", sampleChinese: "他每天下午五点下班。", sampleEnglish: "He gets off work at 5 PM every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下边", english: "below", sampleChinese: "画在下边的是山。", sampleEnglish: "The mountains are drawn below.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下车", english: "get off the car", sampleChinese: "我们现在可以下车了。", sampleEnglish: "We can get off the car now.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下次", english: "next time", sampleChinese: "下次再见！", sampleEnglish: "See you next time!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下课", english: "finish class", sampleChinese: "下课后，我们一起去吃饭。", sampleEnglish: "Let's have dinner together after class.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下午", english: "afternoon", sampleChinese: "我下午要开会。", sampleEnglish: "I have a meeting in the afternoon.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "下雨", english: "rain", sampleChinese: "明天会下雨。", sampleEnglish: "It will rain tomorrow.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "先", english: "first", sampleChinese: "请你先坐下。", sampleEnglish: "Please have a seat first.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "先生", english: "mister", sampleChinese: "这位先生需要帮助。", sampleEnglish: "Mister, do you need assistance?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "现在", english: "now", sampleChinese: "我们现在开始。", sampleEnglish: "We start now.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "想", english: "think, want", sampleChinese: "我想吃冰淇淋。", sampleEnglish: "I want to eat ice cream.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小", english: "small", sampleChinese: "这是一个小狗。", sampleEnglish: "This is a small dog.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小孩儿", english: "child", sampleChinese: "小孩儿们在公园玩得很开心。", sampleEnglish: "The children are playing happily in the park.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小姐", english: "miss, young lady", sampleChinese: "这位小姐在等出租车。", sampleEnglish: "The young lady is waiting for a taxi.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小朋友", english: "child", sampleChinese: "小朋友们都在学校。", sampleEnglish: "The children are all at school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小时", english: "hour", sampleChinese: "我每天锻炼半小时。", sampleEnglish: "I exercise for half an hour every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小学", english: "elementary school", sampleChinese: "小学生学习基础知识。", sampleEnglish: "Elementary school students learn fundamental knowledge.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "小学生", english: "elementary school student", sampleChinese: "这位小学生很聪明。", sampleEnglish: "This elementary school student is very smart.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "笑", english: "laugh", sampleChinese: "他的笑声很响亮。", sampleEnglish: "His laughter is very loud.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "写", english: "write", sampleChinese: "请写下你的名字。", sampleEnglish: "Please write your name.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "谢谢", english: "thank you", sampleChinese: "谢谢你的帮助。", sampleEnglish: "Thank you for your help.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "新", english: "new", sampleChinese: "新一年开始了。", sampleEnglish: "The new year has begun.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "新年", english: "New Year", sampleChinese: "新年快乐！祝你幸福安康。", sampleEnglish: "Happy New Year! Wishing you happiness and good health.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "星期", english: "week", sampleChinese: "星期几是周末？", sampleEnglish: "Which day of the week is the weekend?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "星期日", english: "Sunday", sampleChinese: "星期日是我休息的日子。", sampleEnglish: "Sunday is my day off.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "星期天", english: "Sunday", sampleChinese: "星期天我们去公园。", sampleEnglish: "We're going to the park on Sunday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "行", english: "go", sampleChinese: "走吧，我们准备好了。", sampleEnglish: "Let's go; we're ready.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "休息", english: "rest", sampleChinese: "周末我通常休息一下。", sampleEnglish: "I usually rest a bit on the weekends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "学", english: "study", sampleChinese: "我喜欢学新东西。", sampleEnglish: "I like to study new things.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "学生", english: "student", sampleChinese: "学生们在图书馆学习。", sampleEnglish: "Students are studying in the library.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "学习", english: "learn, study", sampleChinese: "学习是一辈子的事情。", sampleEnglish: "Learning is a lifelong endeavor.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "学校", english: "school", sampleChinese: "我去的学校离家很远。", sampleEnglish: "The school I go to is far from home.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "学院", english: "college", sampleChinese: "这所学院有很多专业。", sampleEnglish: "This college offers many majors.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "要", english: "want, need", sampleChinese: "我要一杯咖啡。", sampleEnglish: "I want a cup of coffee.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "爷爷", english: "grandfather", sampleChinese: "我的爷爷喜欢讲故事。", sampleEnglish: "My grandfather enjoys telling stories.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "也", english: "also", sampleChinese: "我也会游泳。", sampleEnglish: "I can swim too.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "页", english: "page", sampleChinese: "请翻到第十页。", sampleEnglish: "Please turn to page ten.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一", english: "one", sampleChinese: "我有一只猫。", sampleEnglish: "I have one cat.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "衣服", english: "clothing", sampleChinese: "这是我的新衣服。", sampleEnglish: "This is my new clothing.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "医生", english: "doctor", sampleChinese: "医生在医院工作。", sampleEnglish: "Doctors work in the hospital.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "医院", english: "hospital", sampleChinese: "我去医院看望朋友。", sampleEnglish: "I'm going to the hospital to visit a friend.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一半", english: "half", sampleChinese: "一半杯水。", sampleEnglish: "Half a cup of water.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一会儿", english: "a while", sampleChinese: "等一会儿。", sampleEnglish: "Wait a while.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一块儿", english: "together", sampleChinese: "我们去吃饭一块儿。", sampleEnglish: "Let's go eat together.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一下儿", english: "a moment", sampleChinese: "等一下儿，我马上回来。", sampleEnglish: "Wait a moment; I'll be right back.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一样", english: "the same", sampleChinese: "我们穿的衣服一样。", sampleEnglish: "We're wearing the same clothes.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一边", english: "side", sampleChinese: "一边是大海，一边是山。", sampleEnglish: "One side is the sea, the other side is the mountain.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一点儿", english: "a little", sampleChinese: "加一点儿盐。", sampleEnglish: "Add a little salt.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一起", english: "together", sampleChinese: "我们一起学习。", sampleEnglish: "We study together.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "一些", english: "some", sampleChinese: "我想吃一些水果。", sampleEnglish: "I want to eat some fruit.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "用", english: "use", sampleChinese: "用这个刀切面包。", sampleEnglish: "Use this knife to cut the bread.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有", english: "have, there is", sampleChinese: "我有一本书。", sampleEnglish: "I have a book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有的", english: "some", sampleChinese: "有的人喜欢雨天。", sampleEnglish: "Some people like rainy days.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有名", english: "famous", sampleChinese: "这座山很有名。", sampleEnglish: "This mountain is very famous.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有时候", english: "sometimes", sampleChinese: "有时候我喜欢安静。", sampleEnglish: "Sometimes I like it quiet.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有些", english: "some", sampleChinese: "这里有些好吃的。", sampleEnglish: "There is some delicious food here.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "有用", english: "useful", sampleChinese: "这个工具很有用。", sampleEnglish: "This tool is very useful.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "右", english: "right", sampleChinese: "右拐是图书馆。", sampleEnglish: "Turn right for the library.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "右边", english: "right", sampleChinese: "我的包在右边。", sampleEnglish: "My bag is on the right.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "雨", english: "rain", sampleChinese: "雨下得很大。", sampleEnglish: "The rain is heavy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "元", english: "yuan", sampleChinese: "这本书多少元？", sampleEnglish: "How much is this book?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "远", english: "far", sampleChinese: "我家离学校很远。", sampleEnglish: "My home is far from the school.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "月", english: "month", sampleChinese: "这个月有三十一天。", sampleEnglish: "This month has 31 days.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "再", english: "again", sampleChinese: "请再来一杯咖啡。", sampleEnglish: "Please bring another cup of coffee.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "再见", english: "goodbye", sampleChinese: "明天再见！", sampleEnglish: "See you tomorrow!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "在", english: "in, at", sampleChinese: "他在图书馆学习。", sampleEnglish: "He is studying in the library.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "在家", english: "at home", sampleChinese: "星期六我在家休息。", sampleEnglish: "I rest at home on Saturdays.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "早", english: "early", sampleChinese: "早上好！", sampleEnglish: "Good morning!", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "早饭", english: "breakfast", sampleChinese: "我每天吃早饭。", sampleEnglish: "I eat breakfast every day.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "早上", english: "morning", sampleChinese: "我早上喜欢喝咖啡。", sampleEnglish: "I like to drink coffee in the morning.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "怎么", english: "how", sampleChinese: "你怎么了？", sampleEnglish: "What's wrong with you?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "站", english: "stand", sampleChinese: "请站在这里等一下。", sampleEnglish: "Please stand here and wait for a moment.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "找", english: "look for", sampleChinese: "我在找我的手机。", sampleEnglish: "I'm looking for my phone.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "找到", english: "find", sampleChinese: "终于找到了丢失的钥匙。", sampleEnglish: "Finally found the lost keys.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "这", english: "this", sampleChinese: "这是我的书。", sampleEnglish: "This is my book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "这边", english: "here", sampleChinese: "请坐这边。", sampleEnglish: "Please sit here.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "这里", english: "here", sampleChinese: "我在这里等你。", sampleEnglish: "I'm waiting for you here.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "这儿", english: "here", sampleChinese: "他住在这儿。", sampleEnglish: "He lives here.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "这些", english: "these", sampleChinese: "这些是我的朋友。", sampleEnglish: "These are my friends.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "着", english: "continuous aspect marker", sampleChinese: "她正在做饭。", sampleEnglish: "She is cooking.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "真", english: "real", sampleChinese: "这个故事是真的吗？", sampleEnglish: "Is this story real?", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "真的", english: "really", sampleChinese: "我真的很喜欢这个礼物。", sampleEnglish: "I really like this gift.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "正", english: "right, just", sampleChinese: "她正忙着工作。", sampleEnglish: "She's busy working right now.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "正在", english: "in the process of", sampleChinese: "他正在学习中文。", sampleEnglish: "He is learning Chinese.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "知道", english: "know", sampleChinese: "我知道答案。", sampleEnglish: "I know the answer.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "知识", english: "knowledge", sampleChinese: "学习知识是一种快乐。", sampleEnglish: "Learning knowledge is a joy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中", english: "middle, center", sampleChinese: "他站在中间。", sampleEnglish: "He stands in the middle.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中国", english: "China", sampleChinese: "中国是一个有悠久历史的国家。", sampleEnglish: "China is a country with a long history.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中间", english: "middle", sampleChinese: "桌子中间有一束鲜花。", sampleEnglish: "There's a bouquet of flowers in the middle of the table.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中文", english: "Chinese language", sampleChinese: "学习中文很有趣。", sampleEnglish: "Learning Chinese is interesting.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中午", english: "noon", sampleChinese: "我们中午吃午餐。", sampleEnglish: "We have lunch at noon.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中学", english: "middle school", sampleChinese: "中学生学习各种学科。", sampleEnglish: "Middle school students study various subjects.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "中学生", english: "middle school student", sampleChinese: "这位中学生在图书馆学习。", sampleEnglish: "This middle school student is studying in the library.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "重", english: "heavy", sampleChinese: "这箱子很重。", sampleEnglish: "This box is very heavy.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "重要", english: "important", sampleChinese: "健康对我们很重要。", sampleEnglish: "Health is important to us.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "住", english: "live", sampleChinese: "我住在城市中心。", sampleEnglish: "I live in the city center.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "准备", english: "prepare", sampleChinese: "我要准备晚餐。", sampleEnglish: "I need to prepare dinner.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "桌子", english: "table", sampleChinese: "这是我们用来吃饭的桌子。", sampleEnglish: "This is the table we use for eating.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "字", english: "character", sampleChinese: "这个字很难写。", sampleEnglish: "This character is hard to write.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "子", english: "child", sampleChinese: "她有两个子。", sampleEnglish: "She has two children.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "走", english: "walk", sampleChinese: "我喜欢在公园散步。", sampleEnglish: "I like to walk in the park.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "走路", english: "walk", sampleChinese: "我通常走路上班。", sampleEnglish: "I usually walk to work.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "最", english: "most", sampleChinese: "这是我最喜欢的书。", sampleEnglish: "This is my most favorite book.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "最好", english: "best", sampleChinese: "早睡早起身体最好。", sampleEnglish: "Early to bed and early to rise is best for your health.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "最后", english: "last", sampleChinese: "最后一天是星期天。", sampleEnglish: "The last day is Sunday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "昨天", english: "yesterday", sampleChinese: "昨天我去了博物馆。", sampleEnglish: "I went to the museum yesterday.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "左", english: "left", sampleChinese: "请左转。", sampleEnglish: "Please turn left.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "左边", english: "left", sampleChinese: "我的书包在左边。", sampleEnglish: "My backpack is on the left.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "坐", english: "sit", sampleChinese: "请坐下休息。", sampleEnglish: "Please sit down and rest.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "坐下", english: "sit down", sampleChinese: "坐下，别担心。", sampleEnglish: "Sit down, don't worry.", rightInARow: 0, nextReviewDate: Date.now() },
    { chinese: "做", english: "do", sampleChinese: "我要做我的作业。", sampleEnglish: "I need to do my homework.", rightInARow: 0, nextReviewDate: Date.now() },
];

